
==== {modelSupermicro-server-node} Rack Servers

{modelSupermicro-server-node-URL}

.Ultimate Flexibility
*       CPU: Up to 270W and 40 cores
*       Memory: 4TB DDR4-3200 memory in 16 DIMM slots w/ support of Intel Optane PMEM 200 series
*       Storage: Up to 10x all hybrid drive bays (NVMe/SAS/SATA) + Flexible internal storage options (dual NVMe M.2 / SATADOM)
*       Expansion: Up to 2 standard PCIe 4.0 FHHL expansion slots + 2 AIOM for OCP 3.0 NIC; Building block solution for different applications and environment
*       860W Platinum level redundant PWS

.Efficient and Cost-Effective
*       Cost optimized for large volume deployment
*       Tool-less mechanical design for rapid deployment
*       Hot-swap storage and PWS for easy maintenance.
*       IPMI, serial port and service tag for easy management

.Compact
*       Compact system design makes no waste of internal space
*       < 600mm chassis depth
*       Fully utilized system resource with 12 NVMe, 4 PCIe 4.0 x16 + 2 PCIe 4.0 x8 expansion

.Secure
*       Security is top priority
*       TPM 1.2/2.0, signed firmware, Silicon Root of Trust
*       Secure Boot, System Erase
*       FIPS Compliance, Trusted Execution Environment

.Application Ready
*       Balanced architecture between CPUs and optimized for scalable compute, database, GPU, tiered storage and I/O intensive applications
*       Support open standards like OpenBMC and OCP 3.0

.Keep it Green
*       Optimized thermal design
*       High efficiency Platinum level PWS (AC/DC)
*       Reduced waste with bulk packaging and customizable accessories
