
== Component model

ifdef::focusRKE1[]
FixMe-This section describes the various components being used to create a {pn_RKE1} deployment, in the perspective of top to bottom ordering. Once completed, the {pn_RKE1} instance enables the management of multiple Kubernetes clusters, as shown in the following figure:
endif::focusRKE1[]

=== Component overview

By utilizing:

* Kubernetes Platform - {pn_RKE1}
ifndef::GS[]
* Operating System - ifdef::iSLES[{pn_SLES}] ifdef::iSLEMicro[{pn_SLEMicro}}]
* Compute Platform
endif::GS[]

one can create the necessary infrastructure and services. Further details for these components are described in the following sections.

ifdef::SWComp[]

=== Software - {pn_RKE1}

include::../SUSE/RKE1/SA.adoc[]

ifdef::RC,RI[]
As {pn_RKE1} relies upon being deployed on a Kubernetes platform, the next section describes such a suggested component layer.
endif::RC,RI[]
ifdef::GS[]
As {pn_RKE1} can be deployed on a single node, only some prerequisites for the underlying operating system are needed and will be detailed in the deployment section.
endif::GS[]

ifndef::GS[]

ifdef::iSLEMicro[]
=== Software - {pn_SLEMicro}

include::../SUSE/SLE-Micro/SA.adoc[]

With the flexibility of {pn_SLEMicro}, multiple compute platform variants can be considered, as outlined in the next section.

endif::iSLEMicro[]

////
Depending on the number and complexity of the components this proceeding section might better be represented as a table with brief descriptions.   Fewer components can be expressed in short paragraph form.
////

////

===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...
////

endif::GS[]

endif::SWComp[]

ifdef::HWComp[]
ifndef::GS[]

=== Compute Platform

Leveraging the enterprise grade functionality of the operating system mentioned in the previous section, many compute platforms can be the foundation of the deployment:

ifndef::iIHV[]
* Virtual machines on supported hypervisors or hosted on cloud service providers
* Physical, baremetal or single-board computers, either on-premise or hosted by cloud service providers

include::../SUSE/YES.adoc[]
endif::iIHV[]

ifdef::RC[]
ifdef::iIHV[]
ifdef::IHV-Cisco[include::../IHV/Cisco/SA-RA-CompMod.adoc[]]
ifdef::IHV-DELL[include::../IHV/DELL/SA-RA-CompMod.adoc[]]
ifdef::IHV-HPE[include::../IHV/HPE/SA-RA-CompMod.adoc[]]
ifdef::IHV-Fujitsu[include::../IHV/Fujitsu/SA-RA-CompMod.adoc[]]
ifdef::IHV-Supermicro[include::../IHV/Supermicro/SuperServer/SA-RA-CompMod.adoc[]]
endif::iIHV[]

// ifdef::iCSP[]
// FixMe - CSP
// endif::iCSP[]

NOTE: A sample bill of materials, in the <<Appendix>>, cites the necessary quantites of all components, along with a reference to the minimum resource requirements needed by the software components.
endif::RC[]

////
Provide a description of the Systems used and their position in the solution.  Each system should explain why the characteristics of that system is a good fit for the SW Component or architecture.
////

endif::GS[]
endif::HWComp[]

////
===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...

////

