
== Component model

This section describes the various components being used to create a {pn_Rancher} solution deployment, in the perspective of top to bottom ordering. When completed, the {pn_Rancher} instance enables the management of multiple, downstream Kubernetes clusters.

=== Component overview

By using:

ifdef::RC,RI,GS[]
* Software
** Multi-cluster Management Server - {pn_Rancher}
ifdef::GS[]
** Linux Operating System
endif::GS[]
ifndef::GS[]
** Kubernetes Platform -
ifdef::layerK3s[{pn_K3s}]
ifdef::layerRKE1[{pn_RKE1}]
ifdef::layerRKE2[{pn_RKE2}]
** Linux Operating System -
ifdef::layerSLEMicro[{pn_SLEMicro}]
ifdef::layerSLES[{pn_SLES}]
* Compute Platform
ifdef::RC+iIHV[]
ifdef::IHV-Ampere[** {an_Ampere} {familyAmpere-Altra} Family]
ifdef::IHV-Cisco[** {vn_Cisco} {an_CiscoUCS}]
ifdef::IHV-Dell[** {an_Dell} {familyDell-PE}]
ifdef::IHV-HPE+IHV-HPE-ProLiant[** {vn_HPE} {familyHPE-DL}]
ifdef::IHV-HPE+IHV-HPE-Synergy[** {vn_HPE} {familyHPE-S}]
ifdef::IHV-HPQ[** {vn_HPQ} {modelHPQ-ZCentral4R}]
ifdef::IHV-LNVGY[** {vn_LNVGY} {familyLNVGY-Edge}]
ifdef::IHV-SMCi[** {vn_SMCi} {SMCi-SuperServer}]
endif::RC+iIHV[]
endif::GS[]

you can create the necessary infrastructure and services. Further details for these components are described in the following sections.

ifdef::SWComp[]

=== Software - {pn_Rancher}

include::../SUSE/Rancher/SA.adoc[]

ifdef::GS[]
As {pn_Rancher} can be deployed on a single node, some simple prerequisites for the underlying operating system are needed and will be described in the <<Deployment>> section.
endif::GS[]
ifdef::RC,RI[]
For a production implementation of {pn_Rancher}, deploying upon a Kubernetes platform is required and the next sections describe the suggested component layering approach.
endif::RC,RI[]

ifndef::GS[]

ifdef::layerK3s[]
=== Software - {pn_K3s}

include::../SUSE/K3s/SA.adoc[]

endif::layerK3s[]

//// 
ifdef::layerRKE1[]
=== Software - {pn_RKE1}

include::../SUSE/RKE1/SA.adoc[]

endif::layerRKE1[]

ifdef::layerRKE2[]
=== Software - {pn_RKE2}

include::../SUSE/RKE2/SA.adoc[]

endif::layerRKE2[]
////

ifdef::layerSLEMicro[]
=== Software - {pn_SLEMicro}

include::../SUSE/SLE-Micro/SA.adoc[]

endif::layerSLEMicro[]

ifdef::layerSLES[]
=== Software - {pn_SLES}

include::../SUSE/SLES/SA.adoc[]

endif::layerSLES[]

////
Depending on the number and complexity of the components this proceeding section might better be represented as a table with brief descriptions.   Fewer components can be expressed in short paragraph form.
////

////

===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...
////

endif::GS[]
endif::SWComp[]

ifdef::HWComp[]
ifndef::GS[]

=== Compute Platform

Leveraging the enterprise grade functionality of the operating system mentioned in the previous section, many compute platforms can be the foundation of the deployment:

* Virtual machines on supported hypervisors or hosted on cloud service providers
* Physical, baremetal or single-board computers, either on-premises or hosted by cloud service providers

include::../SUSE/YES-Process.adoc[]
include::../SUSE/YES-Search.adoc[]

ifdef::RC[]
ifdef::iIHV[]
ifdef::IHV-Ampere[include::../IHV/Ampere/SA-RA-CompMod.adoc[]]
ifdef::IHV-Cisco[include::../IHV/Cisco/SA-RA-CompMod.adoc[]]
ifdef::IHV-Dell[include::../IHV/Dell/SA-RA-CompMod.adoc[]]
ifdef::IHV-Fujitsu[include::../IHV/Fujitsu/SA-RA-CompMod.adoc[]]
ifdef::IHV-HPE[include::../IHV/HPE/SA-RA-CompMod.adoc[]]
ifdef::IHV-HPQ[include::../IHV/HPQ/SA-RA-CompMod.adoc[]]
ifdef::IHV-LNVGY[include::../IHV/LNVGY/SA-RA-CompMod.adoc[]]
ifdef::IHV-SMCi[include::../IHV/SMCi/SA-RA-CompMod.adoc[]]
endif::iIHV[]

// ifdef::iCSP[]
// FixMe - CSP
// endif::iCSP[]

NOTE: A sample bill of materials, in the <<Appendix>>, cites the necessary quantites of all components, along with a reference to the minimum resource requirements needed by the software components.
endif::RC[]

////
Provide a description of the Systems used and their position in the solution.  Each system should explain why the characteristics of that system is a good fit for the SW Component or architecture.
////

endif::GS[]
endif::HWComp[]

////
===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...

////

endif::RC,RI,GS[]

