
== Component model

ifdef::focusRKE1[]
This section describes the various components being used to create a {pn_RKE1} solution deployment, in the perspective of top to bottom ordering. Once completed, the {pn_RKE1} instance can be used as the application infrastructure for cloud-native workloads and can be imported into {pn_Rancher} for management.
endif::focusRKE1[]

=== Component overview

By using:

* Kubernetes Platform - {pn_RKE1}
ifndef::GS[]
* Operating System -
ifdef::layerSLEMicro[{pn_SLEMicro}]
ifdef::layerSLES[{pn_SLES}]
* Compute Platform
endif::GS[]

you can create the necessary infrastructure and services. Further details for these components are described in the following sections.

ifdef::SWComp[]

=== Software - {pn_RKE1}

include::../SUSE/RKE1/SA.adoc[]

ifdef::RC,RI[]
While all {pn_RKE1} roles can be installed on a single system, a multi-node cluster, is a more production-like approach and will be described in the deployment section.

ifdef::BP[]
TIP: To improve availability, performance and security, the recommended deployment of a {pn_RKE1} cluster is a pair of nodes for the control plane role, at least three etcd role-based nodes and three or more worker nodes.
endif::BP[]
endif::RC,RI[]

ifdef::GS[]
As {pn_RKE1} can be deployed on a single node, only some prerequisites for the underlying operating system are needed and will be detailed in the deployment section.
endif::GS[]

ifndef::GS[]

ifdef::layerSLEMicro[]
=== Software - {pn_SLEMicro}

include::../SUSE/SLE-Micro/SA.adoc[]
endif::layerSLEMicro[]

ifdef::layerSLES[]
=== Software - {pn_SLES}

include::../SUSE/SLES/SA.adoc[]
endif::layerSLES[]

////
Depending on the number and complexity of the components this proceeding section might better be represented as a table with brief descriptions.   Fewer components can be expressed in short paragraph form.
////

////

===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...
////

endif::GS[]

endif::SWComp[]

ifdef::HWComp[]
ifndef::GS[]

=== Compute Platform

Leveraging the enterprise grade functionality of the operating system mentioned in the previous section, many compute platforms can be the foundation of the deployment:

* Virtual machines on supported hypervisors or hosted on cloud service providers
* Physical, baremetal or single-board computers, either on-premise or hosted by cloud service providers

include::../SUSE/YES-Process.adoc[]
include::../SUSE/YES-Search.adoc[]

ifdef::RC[]
ifdef::iIHV[]
ifdef::IHV-Cisco[include::../IHV/Cisco/SA-RA-CompMod.adoc[]]
ifdef::IHV-Dell[include::../IHV/Dell/SA-RA-CompMod.adoc[]]
ifdef::IHV-HPE[include::../IHV/HPE/SA-RA-CompMod.adoc[]]
ifdef::IHV-Fujitsu[include::../IHV/Fujitsu/SA-RA-CompMod.adoc[]]
ifdef::IHV-SMCi[include::../IHV/SMCi/SA-RA-CompMod.adoc[]]
endif::iIHV[]

// ifdef::iCSP[]
// FixMe - CSP
// endif::iCSP[]

NOTE: A sample bill of materials, in the <<Appendix>>, cites the necessary quantites of all components, along with a reference to the minimum resource requirements needed by the software components.
endif::RC[]

////
Provide a description of the Systems used and their position in the solution.  Each system should explain why the characteristics of that system is a good fit for the SW Component or architecture.
////

endif::GS[]
endif::HWComp[]

////
===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...

////

