
== Component model

This section describes the various components being used to create a {pn_Rancher} solution deployment.

=== Component overview

By utilizing:

ifdef::RC,RI,GS[]
* Software
** Multi-cluster Management Server - {pn_Rancher}
ifdef::GS[]
** Linux Operating System
endif::GS[]
ifndef::GS[]
** Kubernetes Platform -
ifdef::layerK3s[{pn_K3s}]
ifdef::layerRKE1[{pn_RKE1}]
ifdef::layerRKE2[{pn_RKE2}]
** Linux Operating System -
ifdef::layerSLEMicro[{pn_SLEMicro}]
ifdef::layerSLES[{pn_SLES}]
* Compute Platform
endif::GS[]

one can create the necessary infrastructure and services. Further details for these components are described in the following sections.

ifdef::SWComp[]

=== Software - {pn_Rancher}

include::../SUSE/Rancher/SA.adoc[]

ifdef::GS[]
As {pn_Rancher} can be deployed on a single node, some simple prerequisites for the underlying operating system are needed and will be described in the <<Deployment>> section.
endif::GS[]
ifdef::RC,RI[]
Given {pn_Rancher} relies upon being deployed on a Kubernetes platform, the next sections describe the suggested component layering approach.
endif::RC,RI[]

ifndef::GS[]

ifdef::layerK3s[]
=== Software - {pn_K3s}

include::../SUSE/K3s/SA.adoc[]

endif::layerK3s[]

//// 
ifdef::layerRKE1[]
=== Software - {pn_RKE1}

include::../SUSE/RKE1/SA.adoc[]

endif::layerRKE1[]

ifdef::layerRKE2[]
=== Software - {pn_RKE2}

include::../SUSE/RKE2/SA.adoc[]

endif::layerRKE2[]
////

ifdef::layerSLEMicro[]
=== Software - {pn_SLEMicro}

include::../SUSE/SLE-Micro/SA.adoc[]

endif::layerSLEMicro[]

ifdef::layerSLES[]
=== Software - {pn_SLES}

include::../SUSE/SLES/SA.adoc[]

endif::layerSLES[]

////
Depending on the number and complexity of the components this proceeding section might better be represented as a table with brief descriptions.   Fewer components can be expressed in short paragraph form.
////

////

===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...
////

endif::GS[]
endif::SWComp[]

ifdef::HWComp[]
ifndef::GS[]

=== Compute Platform

Leveraging the enterprise grade functionality of the operating system mentioned in the previous section, many compute platforms can be the foundation of the deployment:

ifndef::iIHV[]
* Virtual machines on supported hypervisors or hosted on cloud service providers
* Physical, baremetal or single-board computers, either on-premise or hosted by cloud service providers

include::../SUSE/YES.adoc[]
endif::iIHV[]

ifdef::RC[]
ifdef::iIHV[]
ifdef::IHV-Cisco[include::../IHV/Cisco/SA-RA-CompMod.adoc[]]
ifdef::IHV-DELL[include::../IHV/DELL/SA-RA-CompMod.adoc[]]
ifdef::IHV-HPE[include::../IHV/HPE/SA-RA-CompMod.adoc[]]
ifdef::IHV-Supermicro[include::../IHV/Supermicro/SuperServer/SA-RA-CompMod.adoc[]]
endif::iIHV[]

// ifdef::iCSP[]
// FixMe - CSP
// endif::iCSP[]

NOTE: A sample bill of materials, in the <<Appendix>>, cites the necessary quantites of all components, along with a reference to the minimum resource requirements needed by the software components.
endif::RC[]

////
Provide a description of the Systems used and their position in the solution.  Each system should explain why the characteristics of that system is a good fit for the SW Component or architecture.
////

endif::GS[]
endif::HWComp[]

////
===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...

////

endif::RC,RI,GS[]

