=== Compute Platform

ifdef::RI[]
ifndef::iIHV[]
Preparation(s)::
For each node used in the deployment:

* Validate the necessary CPU, memory, disk capacity, and network interconnect quantity and type are present for each node and its intended role. Refer to the recommended CPU/Memory/Disk/Networking requirements as noted in the {pn_Rancher_HWReqURL}[{pn_Rancher} Hardware Requirements].
* Further suggestions
** Disk : Use a pair of local, direct attached, mirrored disk drives is present on each node (SSDs are preferred); these will become the target for the operating system installation.
** Network : Prepare an IP addressing scheme and optionally create both a public and private network, along with the respective subnets and desired VLAN designations for the target environment.
*** Baseboard Management Controller : If present, consider using a distinct management network for controlled access.
** Boot Settings : BIOS/uEFI reset to defaults for a known baseline, consistent state or perhaps with desired, localized values.
** Firmware : Use consistent and up-to-date versions for BIOS/uEFI/device firmware to reduce potential troubleshooting issues later
endif::iIHV[]
endif::RI[]

ifdef::RC[]
ifdef::iIHV[]
ifdef::IHV-Cisco[include::../IHV/Cisco/SA-RA-Deployment-Hardware.adoc[]]
ifdef::IHV-DELL[include::../IHV/DELL/SA-RA-Deployment-Hardware.adoc[]]
ifdef::IHV-HPE[]
ifdef::IHV-HPE-Synergy[include::../IHV/HPE/SA-RA-Deployment-Hardware.adoc[]]
endif::IHV-HPE[]
ifdef::IHV-Supermicro[]
ifdef::IHV-Supermicro-SuperServer[include::../IHV/Supermicro/SuperServer/SYS-120C-TN10R.adoc[]]
ifdef::IHV-Supermicro-SuperServer[include::../IHV/Supermicro/SuperServer/SYS-620C-TN12R.adoc[]]
endif::IHV-Supermicro[]
endif::iIHV[]

// ifdef::iCSP[]
// FixMe - CSP
// endif::iCSP[]
endif::RC[]

