
ifdef::GS[]
The underlying Linux operating system can be:

* A cloud-host virtual machine (VM) or a bare-metal node
* An on-premise VM or a bare-metal server node
endif::GS[]

ifndef::GS[]
As the base software layer, use an enterprise-grade Linux operating system.
ifdef::layerSLEMicro[For example, {pn_SLEMicro}.]
ifdef::layerSLES[For example, {pn_SLES}.]
endif::GS[]

//-
Preparation(s)::
To meet the solution stack prerequisites and requirements, {companyName} operating system offerings, like
ifdef::layerSLEMicro[link:{pn_SLEMicro_ProductPage}[{pn_SLEMicro}]]
ifdef::layerSLES[link:{pn_SLES_ProductPage}[{pn_SLES}]]
can be utilized.
+
. Ensure these services are in place and configured for this node to use:
+
** Domain Name Service (DNS) - an external network-accessible service to map IP Addresses to hostnames
** Network Time Protocol (NTP) - an external network-accessible service to obtain and synchronize system times to aid in timestamp consistency
** Software Update Service - access to a network-based repository for software update packages. This can be accessed directly from each node via registration to
*** the general, internet-based link:{suseSCCPage}[{companyName} Customer Center] (SCC) or
*** an organization's link:{pn_SUMa_ProductPage}[{pn_SUMa}] infrastructure or
*** a local server running an instance of link:{pn_RMT_DocURL}[{pn_RMT}] ({an_RMT})
+
NOTE: During the node's installation, it can be pointed to the respective update service. This can also be accomplished post-installation with the command-line tool named link:{kb_SUSEConnect}[SUSEConnect].
+
ifdef::GS[]
ifdef::focusRancher,layerRKE1,focusRKE1[]
. On the target node with a default installation of
ifdef::layerSLEMicro[{pn_SLEMicro}]
ifdef::layerSLES[{pn_SLES}]
operating system, log in to the node either as root or as a user with sudo privileges and enable the required container runtime engine
+
ifdef::layerSLEMicro[]
----
sudo transactional-update pkg install docker
sudo reboot
sudo systemctl enable --now docker.service
----
endif::layerSLEMicro[]
ifdef::layerSLES[]
----
sudo SUSEConnect -p sle-module-containers/15.3/x86_64
sudo zypper refresh ; zypper install docker
sudo systemctl enable --now docker.service
----
endif::layerSLES[]
+
** Then validate the container runtime engine is working
+
----
sudo systemctl status docker.service
sudo docker ps --all
----
endif::focusRancher,layerRKE1,focusRKE1[]
endif::GS[]
