
==== {familyHPE-A-URL}[{an_HPE} {familyHPE-A} Systems]
{an_HPE} {familyHPE-A} 4000 Systems is the ideal platform for unstructured data in the age of insight. Unlike others, {an_HPE} {familyHPE-A} 4000 enables organizations to unlock the value of their data, at scale, and with ideal economics. It combines an ultra-dense and flexible architecture optimized for unstructured data with the ability to easily deploy and manage as a single scale-out environment. Enterprises can now run endless data‐centric workloads including real-time and batch analytics, advanced data analytics, artificial intelligence (AI), and large-scale data lakes on a single platform.  The built-in security provides complete protection from any intrusions through the life of the infrastructure. {an_HPE} {familyHPE-A} 4000 is the foundation you need to transform into a data-driven enterprise—it’s a platform with endless data possibilities.


Specific models that offer relevant choices for {useCase} are:

{modelHPE-A4510URL}[{modelHPE-A4510}]::
A 2U ultra-dense and rack-scale system providing the right balance of capacity, performance, and security for your data storage intensive workloads.
{modelHPE-A4200URL}[{modelHPE-A4200}]::
The 2P/1U dense compute standard with exceptional flexibility and unmatched expandability for multi-workload environments.

