ifdef::RA,RC,RI,GS[]

== Introduction

On the digital transformation journey to a full cloud native landscape, utilization of microservices becomes the main approach with the dominant technology for such container orchestration being Kubernetes footnote:[https://kubernetes.io/]
With its large community of developers and abundant features and capabilities, Kubernetes has become the defacto standard and is included across most container-as-a-service platforms.  With all of these technologies in place, both developer and operation teams can effectively deploy, manage and deliver functionality to their end users in a resilient and agile manner.

=== Motivation

ifdef::focusRancher[]
include::./SA-{an_Rancher}.adoc[]
endif::focusRancher[]

ifdef::focusK3s,focusRKE1,focusRKE2[]
include::./SA-Kubernetes.adoc[]
endif::focusK3s,focusRKE1,focusRKE2[]

ifdef::RC[]
Once on such a digital transformation journey, some of the next focus areas are:

ifdef::iISV[]
* Workloads
** Determine how to launch either internally developed containerized, microservice workloads or leverage offerings from Independent Software Vendors ( ISV ).
endif::iISV[]

ifdef::iCSP,iIHV[]
* Compute Platform
** To optimize availability, performance, scalability and integrity, assess current system platforms or acquire and utilize new variations from:
ifdef::iIHV[]
*** Independent Hardware Vendors ( IHV ), such as
ifdef::IHV-Ampere[{vn_Ampere_homePage}[{vn_Ampere}] (R)]
ifdef::IHV-Cisco[{vn_Cisco_homePage}[{vn_Cisco}] (R)]
ifdef::IHV-DELL[{vn_Dell_homePage}[{vn_Dell}] (R)]
ifdef::IHV-Fujitsu[{vn_Fujitsu_homePage}[{vn_Fujitsu}] (R)]
ifdef::IHV-HPE[{vn_HPE_homePage}[{vn_HPE}] (R)]
ifdef::IHV-HPI[{vn_HPI_homePage}[{vn_HPI}] (R)]
ifdef::IHV-IBM[{vn_IBM_homePage}[{vn_IBM}] (R)]
ifdef::IHV-Lenovo[{vn_Lenovo_homePage}[{vn_Lenovo}] (R)]
ifdef::IHV-Supermicro[{vn_SMCi_homePage}[{vn_SMCi}] (R)]
, as the platform for physical, baremetal, hypervisors and virtual machines
endif::iIHV[]
ifdef::iCSP[]
*** Cloud Service Providers ( CSP ), like
ifdef::CSP-Amazon[{pn_EKS_homePage}[{pn_EKS}] (R)]
ifdef::CSP-Google[{pn_GKS_homePage}[{pn_GKS}] (R)]
ifdef::CSP-Microsoft[{pn_AKS_homePage}[{pn_AKS}] (R)]
which can also include baremetal, virtual machines plus hosted Kubernetes services
endif::iCSP[]
endif::iCSP,iIHV[]

endif::RC[]

=== Scope

The scope of this document is to provide a
ifndef::RA[]
complete
ifdef::EA[<<G_EA>>]
ifdef::SS[<<G_EA>>]
including
endif::RA[]
ifndef::RC,RI,GS[]
detailed
ifdef::RA[<<G_RA>>]
for
endif::RC,RI,GS[]
ifndef::RI,GS[]
layered
ifdef::RA+RC[<<G_RC>>]
for
endif::RI,GS[]
ifndef::RC,GS[]
general
ifdef::RA+RI[<<G_RI>>]
of
endif::RC,GS[]
ifndef::RC,RI[]
simplified,
ifdef::RA+GS[<<G_GS>>]
approach for
endif::RC,RI[]
ifdef::focusRancher[]
{pn_Rancher}. This can be done in a variety of solution layered stacks, to become a fundamental component of a managing multiple Kubernetes ecosystems.
endif::focusRancher[]
ifdef::focusK3s[]
{pn_K3s}.
This can be done in a variety of scenarios to create an edge-oriented, lightweight Kubernetes cluster deployment.
endif::focusK3s[]
ifdef::focusRKE1[]
{pn_RKE1}.
This can be done in a variety of scenarios to create an enterprise Kubernetes cluster deployment anywhere.
endif::focusRKE1[]
ifdef::focusRKE2[]
{pn_RKE2}.
This can be done in a variety of scenarios to create an enterprise Kubernetes cluster deployment anywhere to provide a very secure environment.
endif::focusRKE2[]

=== Audience

This document is intended for IT decision makers, architects, system administrators and technicians who are implementing a flexible, software-defined Kubernetes
ifdef::focusRancher[management]
platform. One should still be familiar with the traditional IT infrastructure pillars -- networking, computing and storage -- along with the local use cases for sizing, scaling and limitations within each pillars' environments.

endif::RA,RC,RI,GS[]

////

Reference Architecture

Description of the reference architecture/Solution Name and the partners included in the design and validation.  Provided as a proof point for designing similar production ready solutions with design considerations, implementation suggestion, and best practices.  May include statement regarding consulting, technical support and the intended audiences.
////

////

Enterprise Architecture

Beyond the general introduction/overview, in each of following chapters, content includes how this layer provides the necessary attributes to the one above, details and context for this layer itself, and what requirements are needed by the underlying layer. Thus readers are encouraged to scan the entire document to understand the overall solution, even if only expexpected to focus on a certain layer's aspect.

////

