
ifdef::RA,RC,RI,GS[]

== Business aspect

Agility is driving developers toward more cloud native methodologies that focus on microservices architectures and streamlined workflows. Container technologies, like Kubernetes, embody this agile approach and help enable cloud native transformation.

By unifying IT operations with Kubernetes, organizations realize key benefits like increased reliability, improved security and greater efficiencies with standardized automation. Therefore, Kubernetes infrastructure platforms are adopted by enterprises to deliver:

Cluster Operations::
Improved Production and DevOps efficiencies with simplified cluster usage and robust operations

Security Policy & User Management::
Consistent security policy enforcement plus advanced user management on any Kubernetes infrastructure

Access to Shared Tools & Services::
A high level of reliability with easy, consistent access to a broad set of tools and services

// include problem/value sections per focus

ifdef::focusRancher[]
include::./SA-RA-BPBV-{an_Rancher}.adoc[]
endif::focusRancher[]

ifdef::focusK3s[]
include::./SA-RA-BPBV-{an_K3s}.adoc[]
endif::focusK3s[]

ifdef::focusRKE1[]
include::./SA-RA-BPBV-{an_RKE1}1.adoc[]
endif::focusRKE1[]

ifdef::focusRKE2[]
include::./SA-RA-BPBV-{an_RKE2}.adoc[]
endif::focusRKE2[]

////

== Business aspect

=== Business problem

=== Business value

These business value sections/proposition should address the challenges called out above, with forward looking considerations for ongoing growth and innovation.
////

endif::RA,RC,RI,GS[]
