
==== link:{familyHPE-DL-URL}[{an_HPE} {familyHPE-DL} DL Rack Servers]
The DL family of servers are the most flexible, reliable, and performance-optimized {an_HPE} {familyHPE-DL} rack servers—ever. {an_HPE} continues to provide industry-leading compute innovations. The new {an_HPE} {familyHPE-DL} rack portfolio, with flexible choices and versatile design, along with improved energy efficiencies, ultimately lowers your TCO. Integrated with a simplified, but comprehensive management suite and industry-leading support, the {an_HPE} {familyHPE-DL} rack portfolio delivers a more reliable, fast, and secure infrastructure solution, helps increase IT staff productivity, and accelerates service delivery. In addition, the rack portfolio is performance-optimized for multiapplication workloads to significantly increase the speed of IT operations and enable IT to respond to business needs of any size, faster.

Specific models that offer relevant choices for {useCase} are:

link:{modelHPE-DL380URL}[{an_HPE} {familyHPE-DL} {modelHPE-DL380}]::
The industry-leading {an_HPE} {modelHPE-DL380} 2P/2U server with world-class performance and supreme versatility for multi-workload compute server delivers the latest in security, performance and expandability, backed by a comprehensive warranty. Standardize on the industry's most trusted compute platform. The {an_HPE} {modelHPE-DL380} server is securely designed to reduce costs and complexity, featuring:
** the First, Second, Third Generation Intel Xeon Processor Scalable Family with up to a 60% performance gain1 and 27% increase in cores2
** the {an_HPE} 2933 MT/s DDR4 SmartMemory supporting 3.0 TB
** support of 12 Gb/s SAS, and up to 20 NVMe drive plus a broad range of compute options
** {an_HPE} Persistent Memory offers unprecedented levels of performance for databases and analytic workloads
to run everything from the most basic to mission-critical applications and deploy with confidence. 

link:{modelHPE-DL360URL}[{an_HPE} {familyHPE-DL} {modelHPE-DL360}]::
Adaptable for diverse workloads and environments, the compact 1U {an_HPE} {modelHPE-DL360} server delivers security, agility and flexibility without compromise. It supports:
** the Intel Xeon Scalable processor with up to a 60% performance gain1 and 27% increase in cores2
** along with 2933 MT/s {an_HPE} DDR4 SmartMemory supporting up to 3.0 TB2 with an increase in performance of up to 82%3
** the added performance that {an_HPE} Persistent Memory6, {an_HPE} NVDIMMs7 and 10 NVMe bring, the {an_HPE} {modelHPE-DL360} means business. Deploy, update, monitor and maintain with ease
** automating essential server life cycle management tasks with {an_HPE} OneView and {an_HPE} {vn_HPE_BMC}
to deploy this 2P secure platform for diverse workloads in space constrained environments. 

////
link:{modelHPE-DL325URL}[{modelHPE-DL325}]::
A secure, versatile, single-socket, based on AMD EPYC processors, which delivers an exceptional balance of processor, memory, and I/O for virtualization and data-intensive workloads.

link:{modelHPE-DL385URL}[{modelHPE-DL385}]::
Secure and flexible, this 2P 2U {familyHPE-DL} Server utilizes AMD EPYC processors and delivers advanced performance for virtualization and memory-centric workloads.
////

NOTE: link:{familyHPE-certURL}[{an_HPE} {familyHPE-cert}] outlines the minimum version of SLE required for installation, yet later service pack releases may also be used and supported.

