
==== link:{familyHPE-S-URL}[{an_HPE} {familyHPE-S} Servers]
{an_HPE} {familyHPE-S}, the first Composable Infrastructure, empowers IT to create and deliver new value easily and continuously. This single infrastructure reduces operational complexity for traditional workloads and increases operational velocity for the new breed of applications and services. Through a single interface, {an_HPE} {familyHPE-S} composes compute, storage and fabric pools into any configuration for any application. It also enables a broad range of workloads -- from bare metal, to virtual machines, to containers, to operational models like hybrid cloud and DevOps. {an_HPE} {familyHPE-S} enables IT to rapidly react to new business demands with the following components:

* {an_HPE} {familyHPE-S} 12000 Frames are uniquely architected as Composable Infrastructure (CI) to match the powerful 'infrastructure-as-code' capabilities of the {an_HPE} intelligent software architecture. Flexible access to compute, storage, and fabric resources allows for use and re-purposing. Linking multiple {an_HPE} {familyHPE-S} Frames efficiently scales the infrastructure with a dedicated single view of the entire management network.
** Creating multiple composable domains in the infrastructure can efficiently deliver available resources to the business. HPE Synergy Frames reduce complexity by using intelligent auto-discovery to find all available resources to accelerate workload deployments. This drives IT efficiency as the business grows and delivers balanced performance across resources to increase solution effectiveness. 

* With link:{modelHPE-SY480URL}[{an_HPE} {familyHPE-S} {modelHPE-SY480}] Compute Module, one gains operational efficiency and control, and can deploy IT resources quickly for any workload through a single interface. {an_HPE} {familyHPE-S} is a powerful software-defined solution. {an_HPE} {familyHPE-S} Composable Compute resources create pools of flexible compute capacity that can be configured almost instantly to rapidly provision infrastructure for a broad range of applications. The {an_HPE} {familyHPE-S} {modelHPE-SY480} Compute Module delivers an efficient and flexible two-socket workhorse to support most demanding workloads. Powered by:
** Intel Xeon Scalable Family of processors
** up to 4.5 TB DDR4, more storage capacity and controllers
** a variety of GPU options within a composable architecture
{an_HPE} {familyHPE-S} {modelHPE-SY480} Compute Module is the ideal platform for general-purpose enterprise workload performance now and in the future. 

NOTE: link:{familyHPE-certURL}[{an_HPE} {familyHPE-cert}] outlines the minimum version of SLE required for installation, yet later service pack releases may also be used and supported.

