:docinfo:
include::./common_docinfo_vars.adoc[]

// Variables & Attributes
:title: JupyterLab with SUSE Linux Enterprise: Getting Started
:productname: SLES 15 SP4
:productver: 15 SP4
:partnerprod1: JupyterLab
:partnerprod2: Jupyter Notebook
:author1: Brian Fromme, Technical Alliance Manager, SUSE
:author2: Terry Smith, Partner Solutions Director, SUSE
// Deprecated variables & attributes - do not use
//:subtitle: Fujitsu Machine Learning with SUSE Linux Enterprise and Rancher
//:revdate: August, 2022
//:revnumber: 20220804
//:toc2:
//:toc-title: {title}
//:toclevels: 4

= {title}

== Introduction

=== Motivation

// Why this would be of interest
// Challenges
// Benefits

// TS: There is some good text here (https://medium.com/@olivier.borderies/jupyter-python-in-the-corporate-lan-109e2ffde897) to explain why JupyterLab.  We would just want to integrate in SLE value.

Introducing Machine Learning (ML) into a company strategy is exciting and has potential benefits to bring new information to customers.
But there are many technical challenges to implementing a successful ML stragegy.
Deploying and using software with SUSE Linux Enterprise shouldn't be one of those challenges.
SUSE collaborates with project communities and partners to make leveraging these technologies together to be easier to understand, achievable, and repeatable.


You might be wondering why we don't just dive into an ML tookit in this document.
In one way, we think that we have.
Jupyter notebooks and JupyterLab are tools that help your company to share data, ideas, experiments, and code.
Futhermore, Jupyter notebooks are self-documenting instructions that promote collaboration and automation of enterprise processes in a uniform way.


=== Scope

This guide illustrates how to install, configure, and access JupyterLab on SUSE Linux Enterprise (SLE).
We believe that scientists and engineers working with machine learning tend to rely on leading-edge, open source tools.
But enterprises taking projects to production need stability, security, and support.
With this in mind, we target using {productname} in this guide.
Many of the steps herein may be followed with little or no modification on the corresponding version of openSUSE Leap.


=== Audience

This guide is intended for developers, data scientists, ML researchers, and others interested in leveraging the JupyterLab next generation, interactive, computational notebook environment.
The deployment instructions in this document assume only an introductory understanding of Linux commands.


== Prerequisites

// TS: Let's scrap the technical overview for this guide.  It doesn't seem helpful.  Instead, let's jump into prerequisites.

// Description
// TS: Perhaps, describe JupyterLab here, talk about how it's accessed through the web browser, and include a screenshot.
// TS: It probably wouldn't hurt to discuss that JupyterLab also supports other kernels besides Python, such as R and Julia, but I would recommend focusing only on iPython.

// Architecture diagram - TS: This doesn't seem necessary in this doc.  Use a screenshot of the interface instead.

// Minimum requirements (prerequisites) for this guide
// * Requirement 1 https://url[url]
// * Requirement 2 https://url[url]

// BF: I'm not sure how to expand on this list yet. I think I will come back to this later.
// Computer system - should we include any specs?
// > TS: I would be very general.  Perhaps, we drop the computer system from thelist, as it is obvious.
// Internet access - not much else to say, except maybe access to PyPI
// SUSE Linux Enterprise Server 15 SP4 - we are specifically documenting SLES 15 SP4. SLED 15 SP4 and openSUSE Leap 15.4 or Tumbleweed would also work.


For this guide, you need:

* SUSE Linux Enterprise Server {productver} or the corresponding version of openSUSE Leap.

** If you do not already have SLES, installation instructions can be found here:  https://documentation.suse.com/sles/15-SP4/html/SLES-all/book-deployment.html

** Make sure your SLES installation is up-to-date by running `zypper patch`, `zypper update`, or by using https://documentation.suse.com/sles/15-SP4/html/SLES-all/cha-onlineupdate-you.html[YaST online update].

* Python3
Python 3.6 is included with {productname} and is used in this guide.
This is adequate to run JupyterLab and many ML toolkits.
+
[NOTE]
====
Legacy Python 2.x can also be installed on your system.
To avoid confusion and to avoid accidentally calling legacy Python 2.x, this guide uses version-explicit commands, like `python3` and `pip3`.
====

* Access to https://pypi.org/[The Python Package Index (PyPI)].
PyPI is a public repository of software for the Python programming language.



== Setting up your Python environment

ML toolkits are in fast development and often have strict version dependencies.
Installing dependent packages to support one project may, thus, break another project.
For this reason, developers need a way to create isolated environments where they can install the packages they need without impacting other projects or systems operations.

[WARNING]
====
Your application may have a hard dependency for a specific version of the Python interpeter itself.

Installing different versions of Python on your system could break system tools, which have their own dependencies.

To mitigate this risk, SUSE names the Python binaries explicitly.

For example, the default Python interpeter binary is actually the file, 'python3.6'.
This is symbolically linked as 'python3' to simplify usage and offer consistency.

Maintaining multiple versions with a tool like, https://github.com/pyenv/pyenv[pyenv], is out of scope for this guide.
====


=== Creating a Python virtual environment

The https://docs.python.org/3/tutorial/venv.html[Python venv module] provides a mechanism for creating lightweight "virtual environments" and gives us a tool for isolating software dependencies.
See the https://peps.python.org/pep-0405/[Python Enhancement Proposal 405 - Python Virtual Environments] for more details on the venv module.

Creating a Python virtual environment is easy.
Run the following commands as your user (root access is not required):

. Create a virtual environment, named 'python3-ai'.
+
[source,bash]
----
python3 -m venv $HOME/python3-ai
----
+
This creates a new 'python3-ai' subdirectory in your home directory and populates it with files, subdirectories, and symbolic links to enable the virtual environment.

. Change to the new directory.
+
[source, bash]
----
cd $HOME/python3-ai
----

. Activate the new virtual environment.
+
[source, bash]
----
source ./bin/activate
----
+
The 'activate' script cannot be run on its own and must be "sourced" in order to update current environment variables in support of the isolated environment.
+
[TIP]
====
When your virtual environment is active, your command prompt is prefixed with the environment name.
In the present example, you should see '(python3-ai)' before your normal prompt.
====

. Deactivate your active virtual environment.
+
[source, bash]
----
deactivate
----
+
When you are done working in this virtual environment, you can use the `deactivate` command to reset all the environment changes (including your prompt).
This does not delete the virtual environment.
To reactivte it, simply source the activte script again.

You can use the Python venv module to create as many virtual environments as you need, each in its own working directory.


[NOTE]
====
If you no longer need a virtual environment and want to delete it, simply:

. Deactivate the environment.
. Delete its working directory.
====



=== Managing Python packages

Python is not the only language or even the best language for all ML software development.
But Python is popular among ML developers for its simplicity, elegance, and its large open source community of active developers and users.
ML developers also benefit greatly from a wealth of open source code, much of which has been packaged for easy use in other software.

The {productname} repositories include many of these Python packages, tested against the included version of Python.
These Python packages are perfect if the version matches what you need for your project and you are installing them system-wide.


The https://pypi.org/[Python Package Index (PyPI)] is a public repository of open source licensed packages made available by a community of developers from around the world.
There are many ways to install Python packages from PyPI, but the preferred method is with the `pip` command.

In this guide, you will use the `pip` command to install packages from PyPI into your active virtual environment, isolating them from the rest of your system and other virtual environments.
See the https://pip.pypa.io/en/stable/[pip documentation] for more details on this powerful tool.


In the following commands, you will perform some basic operations with `pip`.

. Activate your virtual environment.
+
[source, bash]
----
cd $HOME/python3-ai
source ./bin/activate
----

. Upgrade the `pip` command itself to the latest version.
+
[source, bash]
----
pip3 install --upgrade pip
----

. Install a specific version of the https://pypi.org/project/numpy/1.18.5/[numpy] package.
+
[source, bash]
----
pip3 install numpy==1.18.5
----

. Upgrade to the latest compatible version of numpy.
+
[source, bash]
----
pip3 install --upgrade numpy
----

. Uninstall numpy.
+
[source, bash]
----
pip3 uninstall numpy
----


[NOTE]
====
`pip` is capable of determining and installing the dependencies of packages and will attempt to resolve dependency conflicts.
====


==== Python Tool Versions and Dependencies
// TS: Brian, move this section below the installation and verification of JupyterLab.  Focus on creating a repeatable, sharable environment by preserving the precise package requirements.

.Advanced: Python Tool Versions and Dependencies:
====
Python tools have dependencies on other Python components.
For that reason, you might also consider the advanced topic of managing the versions of your Python tools.
The idea is to capture your tool dependencies and be able to redeploy those later.
To do this, we would leverage one of two Python tools:  'pip freeze' or 'pipreqs'

Information about the use of 'pip freeze' can be found here: https://pip.pypa.io/en/stable/cli/pip_freeze/
Information about the use of 'pipreqs' can be found here: https://pypi.org/project/pipreqs/
====

TIP: You do not need to keep track of all your tool dependencies. You can always deploy a new virtual environment, if needed.

=== Install and launch JupyterLab

Jupyter notebooks are collaboration tools, typically used for science and computing domains.
JupyterLab is the latest web-based interactive development environment for notebooks, code, and data.
You can read more about JupyterLab here: https://jupyter.org/
Through JupyterLab, you can define workflows in data science, scientific computing, computational journalism, and ML.

To install JupyterLab, please make sure you have read and completed the steps outlined above before proceeding.

. Install JupyterLab.
+
[source, bash]
----
pip3 install jupyterlab
----

. Launch JupyterLab
+
[source, bash]
----
jupyter-lab
----


// TS: For installation, use https://jupyter.org/install as a guide.
// TS: Create a Python virtual environment with the `venv` module and also include steps for saving the configuration with `pip freeze` for repeatable configurations.
// TS: We could also discuss `pipenv`: https://pipenv.pypa.io/en/latest/.
// TS: I would not introduce conda or mamba.
// TS: Oh, focus on Python3, not Python2.


== Use case and demonstration

Next we will explore an example use case to show how you can use JupyterLab in your machine-learning project.
We have choose a simple https://en.wikipedia.org/wiki/Logistic_regression[logistic regression,role=external,window=_blank]
   example from the https://www.kaggle.com[Kaggle,role=external,window=_blank] competition website.

First, we will run Jupyter, via the command:

.JupyterLab execution
[source,bash]
----
$ jupyter-lab
----

Then find the browser window that was opened by the preceeding command.
TIP: If you are running SLES on a headless server, you won't be able to see the browser!

Please do experiment with the Jupyter user interface, if you haven't used it before.
Once you are ready, we will experiment with a pre-built Jupyter notebook.


The example is a logistic regression that predicts which passengers survived the Titanic shipwreck.
We hope you find this learning experiment useful.

Next we will run this example on the Kaggle infrastructure, not your own Jupyter installation.
We choose to run this example from the Kaggle website to focus on learning over setup.
The goal is to learn how to manipulate Jupyter notebooks and run experiments, preparing you to build your own.

To load the example notebook, please enter this URL into your browser:
https://www.kaggle.com/code/raman2000/titanic-machine-learning[Titanic - Machine Learning,role=external,window=_blank]

Next, learn more about the notebook and the competition that inspired it here:
https://www.kaggle.com/competitions/titanic[Titanic - Machine Learning from Disaster,role=external,window=_blank]

At this point, you should have enough guidance to begin experiments with Jupyter.
We encourage you to find other examples and play with those too.
At some point, you may want to dive into the code and perhaps even enhance the model.

When you are ready, you can find more examples at:
https://coderefinery.github.io/jupyter/examples/[Examples of Jupyter features,role=external,window=_blank]

Also, here's a more thorough introduction to Jupyter and JupyterLab:
https://coderefinery.github.io/jupyter/[Introduction to Jupyter and JupyterLab,role=external,window=_blank]


//Describe use case and demonstration.
// URL/[Title,role=external,window=_blank]


//[NOTE]
//====
// Use admonitions (i.e., NOTE, TIP, IMPORTANT, CAUTION, WARNING) as needed.
//====

//Use sections to break up major actions, such as:
//=== Prepare the demonstration environment (beyond installation)
//=== Perform action (to illustrate capability)
//=== Examine results (verifying capability)
//Use ordered lists for steps.
//Minimize/consolidate images whenever possible.

// TS: Take a look at https://coderefinery.github.io/jupyter/examples/ for some examples.  Let's keep the example here simple.  We're really focused on just getting JupyterLab with SLE into the mind of the reader for this document.



== Summary

//Summarize the motivation
//Summarize what was demonstrated
//Hint at other capabilities.

Machine Learning is a fascinating and highly-successful technology that companies are putting into practice.
The many advantages of SUSE Linux Enterprise operating systems and Rancher container management are a logical place to develop and deploy ML applications.
This guide is meant to help you to begin your journey into machine learning on SUSE software.
Other guides in this series will help you to utilize various ML toolkits and create containers that land on Rancher Kubernetes Engine.
We will build up to an architecture and explanation for how to employ machine learning in your Edge and/or Digital Transformation projects.

This guide simply showed you how Jupyter notebooks can easily be deployed and we hope you find value in that tool.

SUSE collaborates with Fujitsu to bring you reliable hardware and software infrastructure for the enterprise modernization.
You can count on Fujitsu to deliver a complete solution based on SUSE Linux Enterprise and Rancher software.



== Additional resources

Learn more about the capabilities of Jupyter with these additional references.

// an unordred lists for references
* https://jupyter.org/[Project Jupyter | Home]
* https://coderefinery.github.io/jupyter/[Introduction to Jupyter and JupyterLab]
* https://coderefinery.github.io/jupyter/examples/[Examples of Jupyter features]
* https://www.kaggle.com[Kaggle]
* https://www.kaggle.com/code/raman2000/titanic-machine-learning[Titanic - Machine Learning]


++++
<?pdfpagebreak?>
++++

// Standard SUSE Technical Reference Documents includes

:leveloffset: 0

== Legal notice
include::common_trd_legal_notice.adoc[]

++++
<?pdfpagebreak?>
++++


:leveloffset: 0
include::common_gfdl1.2_i.adoc[]

//end
