:docinfo:
include::./common_docinfo_vars.adoc[]

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// General comments
// Keep in mind that this is a "getting started" guide and the
//   audience that you are trying to reach.
// Leverage ASCIIDoc features to make this document readable and usable:
//   - Text highlights (follow SUSE style guides)
//   - Admonitions (i.e., NOTE, TIP, IMPORTANT, CAUTION, WARNING)
//   - Code blocks
//   - Lists (ordered and unordered, as appropriate)
//   - Links (to other resources)
//   - Images
//     - Place image files under the ./media directory tree
//       (e.g., ./media/src/svg, ./media/src/png)
//     - Format preference: svg > png > jpg
//     - Consolidate images wherever possible
//       (i.e., don't use two images when one conveys the message)
//   - Use sections and subsections to organize and group related
//     steps.
// 
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Document attributes and variables
//
// NOTES:
// 1. Update variables below and adjust docbook file accordingly.
// 2. Comment out any variables/attributes not used.
// 3. Follow the pattern to include additional variables.
//
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// organization - do NOT modify
// -
:trd: Technical Reference Documentation
:type: Getting Started
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// document
// -
:title: Kubeflow on Rancher
:subtitle: Deploying Kubeflow with SUSE Rancher

:product1: Rancher
:product1_full: Rancher by SUSE
:product1_version: 2.7
:product1_url: Primary SUSE product/platform URL (without the protocol)
:product2: Secondary product short name
:product2_full: Secondary product full name
:product2_url: Secondary product URL

:usecase: A few words to identify high level use case (e.g., Database-as-a-Service, edge analytics in healthcare, Kubernetes-native object storage)

:executive_summary: A brief statement of what this document provides (e.g., This document provides a brief introduction to implementing {usecase} with {product2_full} and {product1_full}.)
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// contributor
// specify information about authors, editors, and others here,
// then update docinfo file as appropriate
// -
:author1_firstname: Alex
:author1_surname: Arnoldy
:author1_jobtitle: job title
:author1_orgname: SUSE
:author2_firstname: Mark
:author2_surname: Gonnelly
:author2_jobtitle: job title
:author2_orgname: SUSE
:author3_firstname: Terry
:author3_surname: Smith
:author3_jobtitle: Director, Global Partner Solutions
:author3_orgname: SUSE
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// miscellaneous
// define any additional variables here for use within the document
// -
:k8s_ver: v1.24.9+rke2r2
:kustomize_ver: 5.0.0

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


= {title}: {subtitle}



== Introduction

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Provide a brief statement (1-4 sentences) of the purpose of the guide.
// This is could be the same as the executive summary.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

Machine learning (ML) is driving innovation across many domains.
The importance of ML is reflected by its adoption by the enterprise.
Businesses use ML to achieve deeper insights, grow capabilities, improve efficiencies, and accelerate results.

ML workflows can be complex, and managing them can be difficult.
This is particularly true at production scale.
https://www.kubeflow.org/[Kubeflow] is an open source project that aims to make deploying and scaling ML models as simple as possible.
To achieve this, Kubeflow takes a cloud-native approach, deploying workloads in containers on https://kubernetes.io[Kubernetes] clusters.

The modern, enterprise Kubernetes landscape leverages computing, storage, and networking resources in a variety of environments.

Enterprises continue to expand their Kubernetes resources.
Rancher Prime by SUSE empowers organizations to unify their Kubernetes landscape with secure, streamlined management.


https://www.suse.com/products/harvester/[Harvester by SUSE] is the open source, hyperconverged infrastructure solution that enables enterprises to unify their infrastructure workloads.

By deploying Kubeflow into a https://www.rancher.com/products/rancher[Rancher by SUSE] Kubernetes landscape, you can address the operational and security challenges of managing ML workflows at scale.

[NOTE]
====
*Mark*: Some wordsmithing could be used here.
====


=== Scope

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Specify what this guide covers in no more than 2 sentences.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

This guide details the steps to deploy Kubeflow into an RKE2 Kubernetes cluster managed by Rancher.
After completing these steps, you will be able to access the Kubeflow user interface.


=== Audience

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Identify for whom this document is intended, perhaps with:
//   - topics of interests (e.g., machine learning, security, etc.)
//   - job roles (e.g., developer, administrator, platform architect, etc.)
//   - required skills
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

Data scientists, ML researchers, developers, and operational teams face responsibilities for ensuring ML success.

To be successful with this guide, you should have basic knowledge of Kubernetes operations in a Rancher environment.

[NOTE]
====
*Mark*: Can we be more descriptive of the required skills to use this guide?
====


== Technical overview

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Provide a technical overview of the solution.
// - Identify components.
// - Describe how the components fit together.
//   Leverage diagrams as appropriate, including (but not limited to):
//   - component architecture
//   - data flow diagram
//   - workflow diagram
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

[NOTE]
====
*Mark*:
We should describe the cluster here.
Include an architectural diagram if possible.
====


In this guide, you:

. Verify prerequisites for your environment.

. Deploy an RKE2 cluster on Harvester.

//. Deploy the NFS server.

//. Create the NFS client Container Storage Interface (CSI) on the RKE2 cluster.

. Deploy the MetalLB load-balancer.

. Deploy Istio.

. Deploy Kubeflow.

. Verify access to the Kubeflow user interface.


== Prerequisites

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Identify minimum requirements (prerequisites) the reader
// would need in order to follow the steps of this guide.
// - Link to existing resources whenever possible.
// - Keep this section brief but elaborate as needed.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

[NOTE]
====
*Mark*:
Could we eliminate Harvester from this guide?
Perhaps we could just start with Rancher and deploy an RKE2 cluster on existing nodes?
Also, we should make installing Kustomize a prerequisite, state the version used for the guide, and link to appropriate documentation elsewhere.
====

For this guide, we use Harvester, managed through Rancher, to create a five node RKE2 cluster. However, the same steps should work on any other RKE2 cluster. You will also need a workstation with kubectl and helm installed.



. Install Kustomize on your Linux workstation.

.. Find the lastest release of Kustomize at https://github.com/kubernetes-sigs/kustomize/releases/.
+
[NOTE]
====
This guide leverages Kustomize release {kustomize_ver}.
A newer release should work without issues.
You can try a different release by adjusting the `KUSTOMIZE_RELEASE` variable in the next step.
For example, `KUSTOMIZE_RELEASE="v5.0.1"`.
====

.. Use the following commands to download and install Kustomize for a Linux system with an AMD or Intel processor:
+
[source, console, subs="attributes"]
----
export KUSTOMIZE_RELEASE="{kustomize_ver}"

wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VER}/kustomize_${KUSTOMIZE_VER}_linux_amd64.tar.gz

tar -xvfz kustomize_${KUSTOMIZE_VER}_linux_amd64.tar.gz

sudo mv kustomize /usr/bin/
----


== Deploy an RKE2 cluster with Harvester

[NOTE]
====
*Mark:* Can/Should we remove references to Harvester?
What does Harvester add here for a getting started with Kubeflow guide?
The node characteristics are buried in the text below, move this to the technical overview or prerequisites section.
====


We begin by using the Rancher UI to create a project in Harvester named _kubeflow-on-harvester_ that contains a namespace named _kubeflow-cluster_.
The cluster name should be set to: 
[source, console]
----
kubeflow-on-harvester
----

We define five nodes - three of them for the control plane and two for the workload plane.

* All nodes should be in the same Harvester namespace
* The operating systems for all nodes is the SUSE Linux Enterprise 15 SP4 minimal QCOW2 image with cloud-init enabled (previously known as the OpenStack image)
* All nodes are connected to a single VLAN with DHCP, DNS, and routing to the Internet
* The three VMs with the roles of control-plane and etcd pool are configured with resources of 4 vCPU, 8GB RAM, 40GB boot drive
* The two VMs that make up the workload-plane pool are configured with 8 vCPU, 16GB RAM, 40GB boot drive
* The SSH user for the O/S image is 
+
[source, console]
----
sles
----

NOTE: The node sizings used here were for basic testing purposes only. It is likely that more CPU and RAM would be required for the workload-plane VMs in particular to support a useful Kubeflow workload.

The following User Data cloud-config (under __Show Advanced__) should be applied to all nodes during RKE2 cluster creation:

[listing]
----
### cloud-init
#cloud-config
chpasswd:
  list: |
    root:SUSE
    sles:SUSE
  expire: false
ssh_authorized_keys:
  - >-
    <REPLACE WITH SSH PUBLIC KEY OF THE WORKSTATION>
runcmd:
  - SUSEConnect --url <REPLACE WITH RMT SERVER ADDRESS>
  - zypper -n in -t pattern apparmor
  - zypper -n up
  - zypper in --force-resolution --no-confirm --force kernel-default
  - zypper rm kernel-default-base
----

Configure the Kubernetes `Cluster Configuration` as follows:

. On the __Basic__ tab:

.. Select Kubernetes version {k8s_ver}.
+
[NOTE]
====
This version is currently deprecated but is needed for Harvester Cloud Provider support. If you are not using Harvester, you can select a newer version.
====

.. Enable the Harvester Cloud Provider CSI driver.

.. Set __Container Network__ Interface to `Calico`.

.. Set the __Default Security Pod Policy__ to `unrestricted`.

.. Disable the Nginx Ingress controller under __System Services__.

. On the __Labels and Annotations__ tab:

.. Apply a cluster label where they key is `app` and the value is `kubeflow`. 

. Click __Create__.


After the cluster has been created, verify and reboot the RKE2 nodes:

. SSH to each node as the user `sles`.

. Verify that the `kernel-default` kernel has been installed and `kernel-default-base` kernel has been removed: 
+
[source, console]
----
sudo zypper se kernel-default
----
+
[TIP]
====
After `kernel-default` has been installed, you can remove the `kernel-default-base` kernel with: 
+
[source, console]
----
sudo zypper rm kernel-default-base
----
====

. Verify that all operating system software has been patched to the latest update: 
+
[source, console]
----
sudo zypper up
----

. Reboot each node, in turn to enable the `kernel-default` kernel.

After the RKE2 cluster has been created, gather the KUBECONFIG data from the Rancher Management server and provide it to a workstation with Kubectl and Helm installed.


== Deploy the MetalLB load balancer

MetalLB is a network load-balancer impelementation for Kubernetes clusters on bare metal.
This allows you to create Kubernetes services of the type `LoadBalancer` to provide two important features:

* _address allocation_: MetalLB will take care of assigning individual IP addresses from configured address pools as services are launched and reclaiming those addresses when the services end.

* _external announcement_: MetalLB uses standard network or routing protocols to announce that the IP address is in use by a service.


[NOTE]
====
*Mark*: This is another section that should be placed in a separate file and linked here.
It would be based on Alex's instructions: https://gist.github.com/alexarnoldy/24dd06d8c4291d04c5d7065b520bcb15[Deploy MetalLB].
====


== Validate MetalLB with Longhorn

. Set this variable with the target namespace.
+
[source, console]
----
NAMESPACE="kubeflow"
----

. Create the namespace. 
+
[source, console]
----
kubectl create namespace ${NAMESPACE}
----

. Create the manifest for an nginx pod, PVC, and load balancer service.
+
[source, console]
----
cat <<EOF> nginx-metallb-test.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - mountPath: /mnt/test-vol
          name: test-vol
      volumes:
      - name: test-vol
        persistentVolumeClaim:
          claimName: nginx-pvc


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ${NAMESPACE}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
EOF
----

. Create the pod, service, and the PVC. 
+
[source, console]
----
kubectl apply -f nginx-metallb-test.yaml
----

. Verify the pod is "Running", the `harvester` StorageClass is the `(default)`, the persistentvolumeclaim is `Bound`, and the service has an `EXTERNAL-IP`.
+ 
[source, console]
----
kubectl get pod,sc,pvc,svc -n ${NAMESPACE}
----

. Verify that the service is reachable through the load-balancer IP address from outside the cluster:
+
[source, console]
----
IPAddr=$(kubectl get svc -n ${NAMESPACE} | grep -w nginx | awk '{print$4":"$5}' | awk -F: '{print$1":"$2}')
curl http://${IPAddr} | grep "Thank you"
----
An HTML encoded output should display the phrase "Thank you for using nginx."

. Verify that the volume is mounted in the test pod. 
+
[source, console]
----
TEST_POD=$(kubectl get pods -n ${NAMESPACE} | awk '/nginx/ {print$1}')
kubectl exec -it ${TEST_POD} -n ${NAMESPACE} -- mount | grep test-vol
----
+
The output should show that the volume is mounted at the location `/mnt/test-vol`.

. When finished with testing, delete the pod and service. 
+
[source, console]
----
kubectl delete -f nginx-metallb-test.yaml
----


== Deploy Istio

[NOTE]
====
*Mark*: The single-command Kubeflow installation used in the next section deploys its own Istio.
Therefore, we should remove this section.
====


== Install Kubeflow

[NOTE]
====
*Mark*: This seems like too much of a shortcut in our documentation.
Alex recommended following the https://github.com/kubeflow/manifests#install-with-a-single-command[single command Kubeflow installation].
Let's include that command here, then reference the https://github.com/kubeflow/manifests#installation[Kubeflow Installation] documentation for more details.
====



Follow the instructions at `https://github.com/kubeflow/manifests#installation` to either install all of the Kubeflow components with a single command, or install individual components.


== Enable TLS (HTTPS) on Kubeflow

[NOTE]
====
*Mark*: I've moved content for this section into two separate files (`kubernetes-tls-cert-create.adoc` and `kubernetes-tls-cert-istio.adoc`).
However, I think we decided to delete this section and note that some customers may need TLS ... even though we will not be documenting it here.
====

//Follow the instructions at `https://gist.github.com/alexarnoldy/e84216fa969f849e79ffbcf766e92ffc` to create an applicatoin TLS certificate and private key.
//Be sure to use these variables, while following this procudure:
//+
//[source, console]
//----
//export APP="kubeflow"                            # app name
//export APP_K8S_NAMESPACE="istio-system"          # app namespace
//export APP_SERVICE_NAME="istio-ingressgateway"   # app service name
//export SECRET_NAME="kubeflow-tls"                # app name for secrets
//----

=== Create the TLS certificate

include::kubernetes-tls-cert-create.adoc[]


=== Install the TLS certificate

include::kubernetes-tls-cert-istio.adoc[]


== Validation

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Illustrate functionality with a demonstration.
// Begin with a description or outline of the demonstration.
// Provide clear steps (in ordered lists) for the reader to follow.
// Typical demonstration flow is:
// 1. Prepare the environment for the demonstration.
//    This should be minimal, such as downloading some data to use.
//    If this requires more than a couple steps, consider putting it
//    in a subsection.
// 2. Perform the demonstration.
//    Be careful not to overuse screenshots.
// 3. Verify.
//    This may be interwoven into performing the demonstration.
//
// As with Installation, leverage ordered lists, code blocks,
// admonitions, and screenshots.
//
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


[NOTE]
====
*Mark*: We need to walk the reader through accessing the Kubeflow UI.
This should include at least one screenshot.
====




== Summary

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Summarize:
// - Motivation (1 sentence)
// - What was covered (1-2 sentences)
// - Next steps (unordered list of 2-4 further learning resources)
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

Kubeflow is an important ...







// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Do not modify below this break.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

++++
<?pdfpagebreak?>
++++


:leveloffset: 0

== Legal notice
include::common_trd_legal_notice.adoc[]

++++
<?pdfpagebreak?>
++++


:leveloffset: 0
include::common_gfdl1.2_i.adoc[]

//end
