:docinfo:
include::./common_docinfo_vars.adoc[]

// Variables & Attributes
:title: Ondat with SUSE Rancher
:productname: SUSE Rancher 2.6
:author1: Rodney Karemba, Solutions Architect, Ondat
:author2: Andy King, Alliances Solutions Architect, SUSE
:author3: Terry Smith, Partner Solutions Director, SUSE
:revdate: April 08, 2022
:revnumber: 20220408
//:toc2:
//:toc-title: {title}
//:toclevels: 4


= {title}



== Introduction

=== Motivation

// Why this would be of interest
// Challenges
// Benefits

Ondat is the Kubernetes native persistent storage platform, designed to deliver high performance, guaranteed high availability and security for all your critical stateful workloads.  

Ondat is focused on delivering the best storage solution that is cloud platform agnostic, allowing you to free your data whilst significantly reducing your cloud storage operational costs for stateful applications.   

By combining SUSE Rancher and Ondat, you can experience a complete cloud and Kubernetes native technical stack that does not compromise on the key features modern developers and businesses expect in today's data driven environment.  

Some of the key capabilities that Ondat and SUSE Rancher enable for your data needs include:

* *Data replication and high availability*
+
Leverage resilient storage with automatic failover and healing to ensure uninterrupted access to your data.

* *High performance*
+
Experience top performance with low latency access to data for stateful applications enabling you to run your own databases (e.g., Database-as-a-Service or DBaaS) and other stateful applications in your Kubernetes clusters.

* *Security*
+
Secure your application data with encryption at rest and in transit on a per volume basis.

* *Scalability*
+
Scale your storage horizontally by adding more cluster nodes or vertically by adding more capacity to existing nodes.

* *Platform freedom*
+
Escape infrastructure lock-in with support for all CNCF-certified Kubernetes distributions and cloud platforms.


=== Scope

// This guide will help you take the first steps to 
This guide walks through the basic steps for deploying Ondat with SUSE Rancher and demonstrates the high availability use case with a stateful application.


=== Audience

// This document is intended for 
This document is intended for DevOps engineers, site reliability engineers (SREs), platform engineers, software engineers and developers who are responsible for managing and running stateful workloads in Kubernetes clusters.



== Technical overview

// Architecture diagram

// Description
Ondat uses storage attached to the Kubernetes cluster nodes to create and present persistent, virtual volumes into containers.  Ondat is designed to feel familiar to Kubernetes users - storage is managed through standard StorageClasses and PersistentVolumeClaims, and features are controlled by native Kubernetes Labels  and selectors, prefixed with storageos.com/.  Caching is enabled by default to improve read performance and compressed to reduced network traffic.

Key Ondat components are:

* *Ondat Cluster Operator*
+
Creates and maintains the Ondat storage cluster by ensuring all relevant components are running. 

* *Ondat Controlplane*
+
Monitors and maintains the state of volumes and nodes, working with etcd to maintain state consensus. 

* *Ondat Dataplane*
+
Handles all I/O path related tasks, including reading, writing, compression, and caching. 

* *Ondat Scheduler*
+
Helps ensure applications are scheduled on the same node as their volumes. 

* *CSI Helper*
+
Registers Ondat with Kubernetes as a CSI driver, creating and deleting volumes in response to PersistentVolumeClaims. 

* *Ondat API Manager*
+
Facilitates communication between various APIs and the Ondat Controlplane API.  It continually monitors the state of the cluster and moves it towards the desired state as necessary.



== Prerequisites

// Minimum requirements (prerequisites) for this guide
// * Requirement 1 https://url[url]
// * Requirement 2 https://url[url]

Ensure that you have checked that the following prerequisites have been met before proceeding to the next section. 

* https://www.suse.com/products/suse-rancher/[SUSE Rancher]

** Ensure that you have a SUSE Rancher Kubernetes cluster with at least 3 worker nodes and sufficient https://rancher.com/docs/rancher/v2.6/en/admin-settings/rbac/[Role-Based Access Control (RBAC)] permissions to deploy and manage applications in the cluster.
For more guidance, see the https://rancher.com/docs/rancher/v2.6/en/[Rancher documentation]. 

** Ensure that you have enough block storage available on each of the worker nodes, as Ondat will utilize this to create a single storage pool for storing persistent data. 

NOTE: In this guide, we use SUSE Rancher v2.6.3 with an RKE v1.20.15 cluster that has 3 master nodes and 5 worker nodes for the Ondat install and demonstration. 

* https://www.ondat.io/[Ondat] 

** Ensure that you have met the minimum resource requirements for Ondat to successfully run. Review the main https://docs.ondat.io/docs/prerequisites/[Ondat prerequisites page] for more information. 

** For Ondat to successfully run, ensure that your cluster nodes have the following LinuxIO kernel modules loaded: 

*** target_core_mod 
*** tcm_loop 
*** target_core_file 
*** configfs 
*** target_core_user 
*** uio 

 
* Essential CLI utilities 
Ensure that the following these CLI utilities are installed on your local machine and are available in your $PATH: 

** https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl]

** https://docs.ondat.io/docs/reference/kubectl-plugin/[kubectl-storageos]



== Installation

//Provide steps or link to existing document.
//[source, bash]
//---
//echo "Use code blocks for command-line steps."
//---

Installing Ondat into your SUSE Rancher Kubernetes cluster is easy.  The recommended installation methods are:
1. Through the https://rancher.com/docs/rancher/v2.6/en/helm-charts/[SUSE Rancher Apps & Marketplace] using the https://github.com/rancher/partner-charts/tree/main/charts/ondat-operator/ondat-operator[Ondat Helm Chart].
2. With the https://docs.ondat.io/docs/reference/kubectl-plugin/[Ondat kubectl plugin].


In this guide, you will use the Ondat kubectl plugin to install Ondat and deploy an etcd cluster operator in your SUSE Rancher Kubernetes cluster.


1. Install local path provisioner.
+
By default, a newly provisioned SUSE Rancher Kubernetes cluster does not have a deployed CSI driver.
+
Run the following commands against the cluster to deploy a https://github.com/rancher/local-path-provisioner[Local Path Provisioner] to provide local storage for an etcd cluster.
+
NOTE: The Local Path Provisioner stores all data locally on the individual nodes and is not recommended for production installations. 
+
[source, bash]
----
# Install the local path provisioner.
kubectl apply --filename="https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.21/deploy/local-path-storage.yaml"

# Inspect the status of the pod and storageclass.
kubectl get pod --namespace=local-path-storage
kubectl get storageclass
----


2. Conduct preflight checks.
+
Run the following kubectl-storageos plugin command to conduct preflight checks against the SUSE Rancher Kubernetes cluster to validate that key Ondat prerequisites have been met before proceeding.
+
[source, bash]
----
# Conduct preflight checks.
kubectl storageos preflight
----


3. Create your Ondat credentials.
+
Define and export the __STORAGEOS_USERNAME__ and __STORAGEOS_PASSWORD__ environment variables that will be used as your credentials to access and manage your Ondat instance.
+
[source, bash]
----
export STORAGEOS_USERNAME="admin"
export STORAGEOS_PASSWORD="password"
----


4. Install Ondat.
+
Run the following __kubectl-storageos__ plugin command to install Ondat.
+
[source, bash]
----
# Install Ondat.
kubectl storageos install \
  --include-etcd \
  --etcd-tls-enabled \
  --etcd-storage-class="local-path" \
  --admin-username="$STORAGEOS_USERNAME" \
  --admin-password="$STORAGEOS_PASSWORD"
----
+
NOTE: The installation process may take a few minutes.


5. Verify the Ondat installation.
+
Once installation is complete, inspect Ondat’s resources.  The core components should all show a status of __RUNNING__.
+
[source, bash]
----
# Inspect Ondat resources that have been created.
kubectl get all --namespace=storageos
kubectl get all --namespace=storageos-etcd
kubectl get storageclasses | grep "storageos"
----

6. Apply a licence to the cluster.
+
Newly installed Ondat clusters will run unlicensed for 24 hours without any limitations.
Thereafter, the Ondat cluster must be licensed to ensure that new operations, such as volume provisioning or adding nodes, continue to work.
+
Review the https://docs.ondat.io/docs/operations/licensing[licensing overview] to learn about Ondat licensing and how to obtain a free trial.



== Configuration

Now that you have Ondat successfully deployed and running, you need to create a custom Ondat __StorageClass__ and configure it as the default for the cluster.

This enables key Ondat features, such as:
+
* [Replication](https://docs.ondat.io/docs/concepts/replication/)
* [Topology-Aware Placement (TAP)](https://docs.ondat.io/docs/operations/tap/)
* [Encryption](https://docs.ondat.io/docs/reference/encryption/)


. Define custom region https://docs.ondat.io/docs/reference/labels/[feature labels] for the nodes in the cluster.
+
[source, bash]
----
# Label the worker nodes to define custom regions for the TAP feature.
kubectl label node demo-worker-node-1 custom-region=1 
kubectl label node demo-worker-node-2 custom-region=2
kubectl label node demo-worker-node-3 custom-region=3
kubectl label node demo-worker-node-4 custom-region=1
kubectl label node demo-worker-node-5 custom-region=2

# Check that the worker nodes have been labeled successfully.
kubectl describe nodes | grep "custom-region"
----


. Create a custom Ondat StorageClass, named __ondat-replication__.
+
[source, bash]
----
# Create the Ondat StorageClass.
cat <<EOF | kubectl create --filename -
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ondat-replication
provisioner: csi.storageos.com
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  storageos.com/replicas: "2"
  storageos.com/topology-aware: "true"
  storageos.com/topology-key: "custom-region"
  csi.storage.k8s.io/secret-name: storageos-api
  csi.storage.k8s.io/secret-namespace: storageos
EOF
----


. Mark the custom Ondat StorageClass as default for the cluster.
+
[source, bash]
----
# Set as default.
kubectl patch storageclass ondat-replication -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

# Inspect the StorageClass and ensure it's now the default.
kubectl get storageclasses | grep "ondat-replication"
----


. Install the Ondat CLI utility.

Before the demonstration, deploy and run the https://docs.ondat.io/docs/reference/cli/#run-the-cli-as-a-deployment-in-your-cluster[Ondat CLI utility as a deployment] so that you can interact and manage Ondat through __kubectl__.

.. Deploy the CLI utility in the __storageos__ namespace.
+
[source, bash]
----
# Create the deployment for the Ondat CLI.
cat <<EOF | kubectl create --filename -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageos-cli
  namespace: storageos
  labels:
    app: storageos
    run: cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storageos-cli
      run: cli
  template:
    metadata:
      labels:
        app: storageos-cli
        run: cli
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - "while true; do sleep 3600; done"
        env:
        - name: STORAGEOS_ENDPOINTS
          value: http://storageos:5705
        - name: STORAGEOS_USERNAME
          value: "admin"
        - name: STORAGEOS_PASSWORD
          value: "password"
        image: storageos/cli:v2.5.0
        name: cli
EOF
----

.. Obtain the CLI utility pod name for future reference.
+
[source, bash]
----
# Get the CLI utility pod name.
kubectl --namespace=storageos get pod -ocustom-columns=_:.metadata.name --no-headers -lapp=storageos-cli
----

//ADD output example here




== Demonstration

//Describe use case and demonstration.

Next, you will explore how Ondat with SUSE Rancher helps ensure that stateful workload data are always highly available by:
+
1. Deploying a stateful application that leverages the __ondat-replication__ StorageClass created earlier.
+
2. Simulating a node failure scenario to demonstrate how Ondat's replication feature is able to quickly fail over to a new replica volume when a master volume suddenly goes permanently offline.





== Summary

//Summarize the motivation
//Summarize what was demonstrated
//Hint at other capabilities.



== Additional resources

//Learn more about the capabilities of {title} with these additional references.
//Use an unordred lists for references
//* https://url[reference-title]
//* https://url/[reference-title]


++++
<?pdfpagebreak?>
++++

// Standard SUSE Technical Reference Documents includes

:leveloffset: 0

== Legal notice
include::common_trd_legal_notice.adoc[]

++++
<?pdfpagebreak?>
++++


:leveloffset: 0
include::common_gfdl1.2_i.adoc[]

//end
