==== {an_HPQ} {familyHPQ-Z}
The link:{familyHPQ-Z-URL}[{an_HPQ} {familyHPQ-Z}] portfolio provides extreme performance for the most-demanding professional workflows. But the {familyHPQ-Z} vision goes beyond powerful processing and graphics, cutting-edge thermal design and unrelenting reliability. 

A specific model that offer relevant choices for {useCase} is:

link:{modelHPQ-ZCentral4R-URL}[{an_HPQ} {modelHPQ-ZCentral4R}]::
The industry-leading {an_HPQ} {modelHPQ-ZCentral4R} gives performance in a high-density 1U rack workstation footprint. This slim powerhouse lets you pack in more units — and power. You can maximize your compute investment by centralizing a suite of {modelHPQ-ZCentral4R} that can be accessed remotely with {an_HPQ} ZCentral software. Plus, software certifications for leading apps come standard, delivering professional reliability and predictable licensing fees.

NOTE: The {an_HPQ} {modelHPQ-ZCentral4R} is {companyName} YES Certified Hardware.

** up to 18 cores Intel Xeon W processor - ensure the highest performance and productivity for your pro-level apps and most challenging projects. Avoid system crashes in the middle of your workflow with Error Correction Code (ECC) memory that detects and corrects soft errors in the memory system on the fly.
** up to NVIDIA RTX™ A6000 GPU - reach peak performance with support for one ultra high-end or two mid-tier18 NVIDIA RTX professional graphics options
** up to 256 GB DDR4-2933 SDRAM - get greater application responsiveness to tackle large workloads with quad-channel architecture providing up to 256 GB of memory
** up to 22 TB storage - access and store massive amounts of data on the fly with three storage bays and dual M.2 slots
** an aggregated power option - combine two 675W power supplies that can provide a redundant option, so you'll have power to keep you up and running


