==== {an_Ampere} {familyAmpere-Altra} Family
The link:{familyAmpere-Altra-URL}[{an_Ampere} {familyAmpere-Altra}] Arm v8.2 processor portfolio of world's first cloud native processors is widely available with data center ready configurations from our systems partners and for use with many Cloud Service Providers. Explore the link:{familyAmpere-AltraPlatform-URL}[{vn_Ampere} Platforms] offered from our partners. These systems are flexible enough to meet the needs of any cloud deployment and come packed with {an_Ampere} 80-core {modelAmpere-Altra} or 128-core {modelAmpere-AltraMax} processors.

The specific processor models that offer relevant choices for {useCase} are designed to meet the requirements of modern data centers, deliver predictable performance, high scalability, 
and power efficiency for data center deployments from hyperscale cloud to the edge cloud. These processorst that drive efficiency in your data center infrastructure workloads, 
including data analytics, artificial intelligence, database storage, telco stacks, edge computing, and Web hosting, are:

* {an_Ampere} {modelAmpere-Altra} 64-Bit Multi-Core Processor
** Predictable Performance - {an_Ampere} {modelAmpere-Altra} offers up to 80 cores at up to 3.30 GHz speed maximum. Each core is single-threaded by design with its own 64 KB L1 I-cache, 64 KB L1 D-cache, and a huge 1 MB L2 cache, delivering predictable performance all along by eliminating the noisy neighbor challenge within each core.
** Power Efficiency - provides industry-leading power efficiency/core, while packing 80 cores in a single-socket and 160 cores in a dual-socket platform, establishing new levels of power efficiency with scalability to meet the most strenuous application infrastructure needs.

* {an_Ampere} {modelAmpere-AltraMax} 64-Bit Multi-Core Processor
** Predictable Performance - {an_Ampere} {modelAmpere-AltraMax} offers up to 128 cores operating at a maximum of 3.0 GHz. Each core is single-threaded by design with its own 64 KB L1 I-cache, 64 KB L1 D-cache, and a huge 1 MB L2 cache, delivering predictable performance 100% of the time by eliminating the noisy neighbor challenge within each core.
** Power Efficiency - provides industry-leading power efficiency/core, while packing 128 cores in a single-socket and 256 cores in a dual-socket platform, establishing new levels of power efficiency with scalability.

Furthermore, each of these processors features:

* High Scalability - With leading power/core, and multi-socket support, it provides the scalability to maximize the number of servers per rack, unparalleled in the industry.
* Reliability, Availability, and Serviceability (RAS) - provides extensive enterprise-class RAS capabilities. Data in memory is protected with advanced ECC in addition to standard DDR4 RAS features. End-to-end data poisoning ensures corrupted data is tagged and any attempt to use it is flagged as an error. The SLC is also ECC protected, and the processor supports background scrubbing of the SLC cache and DRAM to locate and correct single-bit errors before they accumulate into uncorrectable errors.

