
=== Performance

FixMe - Integer vitae justo eget magna fermentum iaculis. Elementum facilisis leo vel fringilla est. Non arcu risus quis varius. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Aliquam nulla facilisi cras fermentum odio eu. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Nulla malesuada pellentesque elit eget gravida cum sociis. Urna porttitor rhoncus dolor purus non enim praesent elementum facilisis. Tristique senectus et netus et malesuada fames ac. Pharetra vel turpis nunc eget. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Elementum pulvinar etiam non quam. Vitae tortor condimentum lacinia quis vel eros donec. Amet venenatis urna cursus eget nunc scelerisque viverra. Auctor elit sed vulputate mi sit amet mauris commodo quis. Pharetra diam sit amet nisl suscipit adipiscing bibendum est.

ifdef::FLVR[]

ifdef::PoC[]
include::./PoC/SA.adoc[]
endif::PoC[]

ifdef::Production[]
include::./Production/SA.adoc[]
endif::Production[]

ifdef::Scaling[]
include::./Scaling/SA.adoc[]
endif::Scaling[]

endif::FLVR[]
