//include::./dellpoweredge_vars.adoc[]

==== {modelDell-server-node-R650} Rack Servers

{modelDell-server-node-R650-URL}

The PowerEdge R650 is SUSE YES Certified Hardware.

Compelling performance, high scalability, and density

The Dell EMC PowerEdge R650, is a full-featured enterprise server, designed to optimize workloads performance and data center density

•       CPU: Up to two 3rd Generation Intel Xeon Scalable processors, with up to 40 cores per processor
•       Memory: 32 DDR4 DIMM slots, supports RDIMM 2 TB max or LRDIMM 4 TB max, speeds up to 3200 MT/s, Up to 16 Intel Persistent Memory 200 series (BPS) slots, 8 TB max, Supports registered ECC DDR4 DIMMs only
•       Storage Controllers -  Internal controllers: PERC H745, HBA355I, S150, H345, H755, H755N
•	Storage Controllers -  Boot Optimized Storage Subsystem (BOSS-S2): HW RAID 2 x M.2 SSDs 240 GB or 480 GB
•	Storage Controllers - External PERC (RAID): PERC H840, HBA355E
•       Drive Bays - Front bays: Up to 10 x 2.5-inch SAS/SATA/NVMe (HDD/SSD) max 153 TB, Up to 4 x 3.5-inch SAS/SATA (HDD/SSD) max 64 TB, Up to 8 x 2.5-inch SAS/SATA/NVMe (HDD/SSD) max 122.8 TB
•       Drive Bays - Rear bays: Up to 2 x 2.5-inch SAS/SATA/NVMe (HDD/SSD) max 30.7 TB

For more information, see {modelDell-server-node-R650-datasheet}, {modelDell-server-node-R650-datasheet-URL}

Innovate at scale with challenging and emerging workloads

The Dell EMC PowerEdge R650, powered by the 3rd Generation Intel® Xeon® Scalable processors is the optimal rack server to address application performance and acceleration. The PowerEdge R650, is a dual-socket/1U rack server that delivers outstanding performance for the most demanding workloads. It supports 8 channels of memory per CPU, and up to 32 DDR4 DIMMs @ 3200 MT/s speeds. In addition, to address substantial throughput improvements the PowerEdge R650 supports PCIe Gen 4 and up to 10 NVMe drives with improved air-cooling features and optional Direct Liquid Cooling to support increasing power and thermal requirements. This makes the PowerEdge R650 an ideal server for data center standardization on a wide range of workloads including; Database and Analytics, HighFrequency Trading, Traditional corporate IT, Virtual Desktop Infrastructure, and even HPC or AI/ML environments that require performance, and GPU support in a dense 1U form factor

Increase efficiency and accelerate operations with autonomous collaboration

The Dell EMC OpenManage systems management portfolio tames the complexity of managing and securing IT infrastructure. Using Dell Technologies’ intuitive end-to-end tools, IT can deliver a secure, integrated experience by reducing process and information silos in order to focus on growing the business. The Dell EMC OpenManage portfolio is the key to your innovation engine, unlocking the tools and automation that help you scale, manage, and protect your technology environment.

•	Built-in telemetry streaming, thermal management, and RESTful API with Redfish offer streamlined visibility and
control for better server management
•	Intelligent automation lets you enable cooperation between human actions and system capabilities for added
productivity
•	Integrated change management capabilities for update planning and seamless, zero-touch configuration and
implementation
•	Full-stack management integration with Microsoft, VMware, ServiceNow, Ansible and many other tools

Protect your data assets and infrastructure with proactive resilience

The Dell EMC PowerEdge R650 server is designed with a cyber-resilient architecture, integrating security deeply into every phase in the lifecycle, from design to retirement.

•	Operate your workloads on a secure platform anchored by cryptographically trusted booting and silicon root of trust
•	Maintain server firmware safety with digitally signed firmware packages
• Prevent unauthorized configuration or firmware change with system lockdown
• Securely and quickly wipe all data from storage media, including hard drives, SSDs and system memory with System Erase

