
=== Integrity

FixMe - Vitae suscipit tellus mauris a diam maecenas sed enim ut. Venenatis cras sed felis eget velit. Eget egestas purus viverra accumsan in. Facilisi nullam vehicula ipsum a arcu cursus. Facilisis volutpat est velit egestas dui id. Feugiat nibh sed pulvinar proin gravida. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Gravida dictum fusce ut placerat orci nulla pellentesque. Convallis tellus id interdum velit. Vel facilisis volutpat est velit egestas. Libero volutpat sed cras ornare arcu. Tellus rutrum tellus pellentesque eu tincidunt tortor. Neque ornare aenean euismod elementum nisi quis eleifend quam. Amet purus gravida quis blandit turpis. Blandit massa enim nec dui nunc mattis. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Felis bibendum ut tristique et egestas quis ipsum. Aliquam ultrices sagittis orci a.

ifdef::FLVR[]

ifdef::PoC[]
include::./PoC/SA.adoc[]
endif::PoC[]

ifdef::Production[]
include::./Production/SA.adoc[]
endif::Production[]

ifdef::Scaling[]
include::./Scaling/SA.adoc[]
endif::Scaling[]

endif::FLVR[]
