
==== {familyHPE-DL-URL}[{an_HPE} {familyHPE-DL} DL Rack Servers]
The DL family of servers are the most flexible, reliable, and performance-optimized {an_HPE} {familyHPE-DL} rack servers—ever. {an_HPE} continues to provide industry-leading compute innovations. The new {an_HPE} {familyHPE-DL} rack portfolio, with flexible choices and versatile design, along with improved energy efficiencies, ultimately lowers your TCO. Integrated with a simplified, but comprehensive management suite and industry-leading support, the {an_HPE} {familyHPE-DL} rack portfolio delivers a more reliable, fast, and secure infrastructure solution, helps increase IT staff productivity, and accelerates service delivery. In addition, the rack portfolio is performance-optimized for multiapplication workloads to significantly increase the speed of IT operations and enable IT to respond to business needs of any size, faster.

Specific models that offer relevant choices for {useCase} are:

{modelHPE-DL380URL}[{modelHPE-DL380}]::
The industry-leading 2P/2U server with world-class performance and supreme versatility for multi-workload compute.
{modelHPE-DL360URL}[{modelHPE-DL360}]::
The 2P/1U dense compute standard with exceptional flexibility and unmatched expandability for multi-workload environments.
{modelHPE-DL325URL}[{modelHPE-DL325}]::
A secure, versatile, single-socket, based on AMD EPYC processors, which delivers an exceptional balance of processor, memory, and I/O for virtualization and data-intensive workloads.
{modelHPE-DL385URL}[{modelHPE-DL385}]::
Secure and flexible, this 2P 2U {familyHPE-DL} Server utilizes AMD EPYC processors and delivers advanced performance for virtualization and memory-centric workloads.

