
ifdef::IHV-Fujitsu[]

include::./PRIMERGY_vars.adoc[]

=== {vn_Fujitsu}

Utilizing the above software application and technology solutions with the server platforms offered by {vn_Fujitsu} [ {an_Fujitsu} ] provides many alternative for scale, cost-effectiveness and performance options that could align with local IT staff platform preferences:

* density-optimized - high performance and efficiency for big data and the most demanding workloads
* mission-critical - systems of intelligence to fuel your digital transformation in a world where time and data are the new currency and business continuity is expected
* composable - fully adaptable and ready for Hybrid-IT to future-proof your data center for today's workloads and tomorrow's disruptors
* IoT - realize the potential of the Internet of Things to provide compute at the network edge
* cloud - high-capacity, mass-compute open infrastructure with security and software to match
* and virtualized use cases.

ifdef::IHV-Fujitsu-PRIMERGY

NOTE: {an_Fujitsu} https://www.fujitsu.com/fts/products/computing/servers/primergy/os/linux/suse/[Servers Support & OS Certification Matrices] outlines the minimum version of SLE required for installation, yet later service pack releases may also be used.

include::../../{companyName}/YES.adoc[]

Server product-line and model options abound in the https://www.fujitsu.com/fts/products/computing/servers/[{an_Fujitsu} portfolio], including:

ifdef::IHV-Fujitsu-PRIMERGY[]
include::./PRIMERGY.adoc[]
endif::IHV-Fujitsu-PRIMERGY[]

==== Suggested Platform Models

Even with the broad certification and support model across the range of available {an_Fujitsu} platform models, the following table summarizes which might be a best-practice selection for the various deployment types and sizes (**__S__**mall, **__M__**edium, **__L__**arge, **__XL__**arge).

.{vn_Fujitsu} Platform Matrix for Deployment Types
[width="80%",valign="middle",halign="center",options="header"]
|===

| System Platform |
ifdef::CapOpt[ *_<<G_CapOpt,Capacity Optimized>>_* |] 
ifdef::Balance[ *_<<G_Balance,Balance>>_* |] 
ifdef::PerfOpt[ *_<<G_PerfOpt,Performance Optimized>>_* ] 

ifdef::IHV-Fujitsu-PRIMERGY[]
| PRIMERGY
ifdef::CapOpt[|*_(XL) =_* {modelFujitsu-RX2540}]
ifdef::Balance[|*_(XL) =_* {modelFujitsu-RX2540} *_(L) =_* {modelFujitsu-RX2540}]
ifdef::PerfOpt[|*_(L) =_* {modelFujitsu-RX2540}]
endif::IHV-Fujitsu-PRIMERGY[]

|===

endif::IHV-Fujitsu[]

