
// [glossary]

== Glossary

* Document Scope
ifdef::GS[]
+
[[g-gs,getting started]]Getting Started::
A guide with the basic steps to quickly and simply deploy the one layer of the referenced component of the {companyName} portfolio, with generalized pointers to other required dependency elements.
endif::GS[]
ifdef::RI[]
+
[[g-ri,reference implementation]]Reference Implementation::
A guide with the basic steps to deploy the highlighted components of the {companyName} portfolio, including generalized pointers to other layers and elements. This is considered an introductory approach and a basis for other tested variations.
endif::RI[]
ifdef::RC[]
+
[[g-rc,reference configuration]]Reference Configuration::
A guide with the basic steps to deploy the layered stack of components from both the {companyName} and partner portfolios. This is considered a fundamental basis to demonstrate a specific, tested configuration of components.
endif::RC[]
ifdef::RA[]
+
[[g-ra,reference architecture]] Reference Architectures{wj}footnote:Reference-Architecture[link: https://en.wikipedia.org/wiki/Reference_architecture[Reference Architecture]]::
A guide with the general steps to deploy and validate the structured solution components from both the {companyName} and partner portfolios. This provides a shareable template of consistency for consumers to leverage for similar production ready solutions, including design considerations, implementation suggestions and best practices.
endif::RA[]
ifdef::BP[]
+
[[g-best-practice,best practice]]Best Practice::
Information that can overlap both the {companyName} and partner space. It can either be provided as a standalone guide that provides reliable technical information not covered in other product documentation, based on real-life installation and implementation experiences from subject matter experts or complementary, embedded sections within any of the above documentation types describing considerations and possible steps forward.
endif::BP[]

////
ifdef::DT[]
* FixMe - Deployment Type(s)::
+
ifdef::DT+DT1[]
[[g-dt1]]DT1::
FixMe - Ut morbi tincidunt augue interdum. Donec enim diam vulputate ut pharetra sit amet. Mauris vitae ultricies leo integer. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Et pharetra pharetra massa massa. Sagittis id consectetur purus ut. Et sollicitudin ac orci phasellus egestas tellus. Eu nisl nunc mi ipsum. Nibh cras pulvinar mattis nunc sed blandit libero volutpat sed. Cras adipiscing enim eu turpis egestas pretium aenean. Nulla pellentesque dignissim enim sit. Morbi non arcu risus quis.
endif::DT+DT1[]
+
ifdef::DT+DT2[]
[[g-dt2]]DT2::
FixMe - Sed arcu non odio euismod lacinia at quis. Sodales ut eu sem integer vitae justo. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Et tortor consequat id porta nibh venenatis cras sed felis. Ut aliquam purus sit amet luctus venenatis lectus. Lacus viverra vitae congue eu consequat. At lectus urna duis convallis convallis. Risus nullam eget felis eget. Euismod nisi porta lorem mollis aliquam ut porttitor. Mollis aliquam ut porttitor leo a diam. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Platea dictumst vestibulum rhoncus est.
endif::DT+DT2[]

endif::DT[]
////


ifdef::FCTR[]
* Factor(s)
ifdef::FCTR+Automation[]
+
[[g-automation,Automation]]Automation{wj}footnote:Automation[link: https://en.wikipedia.org/wiki/Infrastructure_as_code[Infrastructure-as-Code]]::
Infrastructure automation enables speed through faster execution when configuring the infrastructure and aims at providing visibility to help other teams across the enterprise work quickly and more efficiently. Automation removes the risk associated with human error, like manual misconfiguration; removing this can decrease downtime and increase reliability. These outcomes and attributes help the enterprise move towards implementing a culture of DevOps, the combined working of development and operations.
endif::FCTR+Automation[]
ifdef::FCTR+Availability[]
+
[[g-availability,Availability]]Availability{wj}footnote:Availability[link: https://en.wikipedia.org/wiki/Availability[Availability]]::
The probability that an item operates satisfactorily, without failure or downtime, under stated conditions as a function of its reliability, redundancy and maintainability attributes. Some major objectives to achieve a desired service level objectives are:
+
** Preventing or reducing the likelihood and frequency of failures via design decisions within the allowed cost of ownership
** Correcting or coping with possible component failures via resiliency, automated failover and disaster-recovery processes
** Estimating and analyzing current conditions to prevent unexpected failures via predictive maintenance
endif::FCTR+Availability[]
ifdef::FCTR+Integrity[]
+
[[g-integrity,Integrity]]Integrity{wj}footnote:Integrity[link: https://en.wikipedia.org/wiki/Data_integrity[Data Integrity]]::
Integrity is the maintenance of, and the insurance of the accuracy and consistency of a specific element over its entire lifecycle. Both physical and logical aspects must be managed to ensure stability, performance, re-usability and maintainability.
endif::FCTR+Integrity[]
ifdef::FCTR+Performance[]
+
[[g-performance,Performance]]Performance{wj}footnote:Performance[link: https://en.wikipedia.org/wiki/Performance_engineering[Performance Engineering]]::
In the context of a system's expected life cycle, performance is an assessment of transactions, responsiveness and underlying stability of the provider technology while doing tuning and adjustments. Other risk factors and discerning potential impacts to surrounding use cases are also integral parts of the profile to address beyond service levels, capacity and problem management.
endif::FCTR+Performance[]
ifdef::FCTR+Security[]
+
[[g-security,Security]]Security{wj}footnote:Security[link: https://en.wikipedia.org/wiki/Security[Security]]::
Security is about ensuring freedom from or resilience against potential harm, including protection from destructive or hostile forces. To minimize risks, one mus manage governance to avoid tampering, maintain access controls to prevent unauthorized usage and integrate layers of defense, reporting and recovery tactics.
endif::FCTR+Security[]

endif::FCTR[]

ifdef::FLVR[]
* Deployment Flavor(s)
+
ifdef::FLVR+PoC[]
[[g-poc,proof-of-concept]]Proof-of-Concept{wj}footnote:Proof-of-Concept[link: https://en.wikipedia.org/wiki/Proof_of_concept[Proof of Concept]]::
A partial or nearly complete prototype constructed to demonstrate functionality and feasibility for verifying specific aspects or concepts under consideration.  This is often a starting point when evaluating a new, transitional technology. Sometimes it starts as a Minimum Viable Product (MVP{wj}footnote:[link: https://en.wikipedia.org/wiki/Minimum_viable_product[Minimum Viable Product]]) that has just enough features to satisfy an initial set of requests. After such insights and feedback are obtained and potentially addressed, redeployments may be utilized to iteratively branch into other realms or to incorporate other known working functionality.
endif::FLVR+PoC[]
+
ifdef::FLVR+Production[]
[[g-production,production]]Production::
A deployed environment that target customers or users can interact with and rely upon to meet their needs, plus be operationally sustainable in terms of resource usage and economic constraints.
endif::FLVR+Production[]
+
ifdef::FLVR+Scaling[]
[[g-scaling,scaling]]Scaling::
The flexibility of a system environment to either vertically scale-up, horizontally scale-out or conversely scale-down by adding or subtracting resources as needed. Attributes like capacity and performance are often the primary requirements to address, while still maintaining functional consistency and reliability.
endif::FLVR+Scaling[]

endif::FLVR[]

