== Summary

Using components and offerings from link:{suseHomePage}[{companyName}] and the {portfolioName} portfolio
ifdef::RC+iIHV[]
ifdef::IHV-Dell[plus link:{modelDell-server-node-all-URL}[{an_Dell} {familyDell-PE}] Rack Servers]
ifdef::IHV-HPE[]
ifdef::IHV-HPE-ProLiant[plus link:{familyHPE-DL-URL}[{vn_HPE} {familyHPE-DL} Rack Servers]]
ifdef::IHV-HPE-Synergy[plus link:{familyHPE-S-URL}[{vn_HPE} {familyHPE-S} Servers]]
endif::IHV-HPE[]
ifdef::IHV-SMCi[plus link:{SMCi-SuperServer-URL}[{SMCi-SuperServer}] Rack Servers]
endif::RC+iIHV[]
streamline the ability to quickly and effectively engage in a digital transformation, taking advantage of cloud-native resources and disciplines. Using such technology approaches lets you deploy and leverage transformations of infrastructure into a durable, reliable enterprise-grade environment.

Simplify::
Simplify and optimize your existing IT environments

ifdef::focusRancher[]
* Using {pn_Rancher} enables you to simplify Kubernetes cluster deployment and management of the the infrastructure components.
endif::focusRancher[]
ifdef::focusK3s[]
* Using {pn_K3s} enables you to quickly and simply deploy a Kubernetes cluster in a wide array of locations, across edge, branch, core and cloud.
endif::focusK3s[]
ifdef::focusRKE1[]
* Using {pn_RKE1} enables you to simplify, maintain and scale Kubernetes cluster deployments in a supportable fashion.
endif::focusRKE1[]
ifdef::focusRKE2[]
* Using {pn_RKE2} enables you to simplify, maintain and scale Kubernetes cluster deployments in a supportable fashion, with a primary focus on security aspects as well.
endif::focusRKE2[]

Modernize::
Bring applications and data into modern computing

ifdef::focusRancher[]
* With {pn_Rancher}, the digital transformation to containerized applications can extended, in a distributed computing context, to benefit from the ability both to manage many target clusters, for each of the respective user bases and to facilitate the actual workload deployments.
endif::focusRancher[]
ifdef::focusK3s[]
* With {pn_K3s}, the digital transformation to containerized applications can progress since both developers and production can leverage these deployments for the actual workloads.
endif::focusK3s[]
ifdef::focusRKE1[]
* With {pn_RKE1}, the digital transformation to containerized applications can benefit from the provided, production-quality application infractructures for each of the respective user bases and to facilitate the actual workload deployments and resilient usage.
endif::focusRKE1[]
ifdef::focusRKE2[]
* With {pn_RKE2}, the digital transformation to containerized applications can benefit from the provided, production-quality application infractructures for each of the respective user bases and to facilitate the actual workload deployments and resilient usage.
endif::focusRKE2[]

Accelerate::
Accelerate business transformation through the power of open source software

ifdef::focusRancher[]
* Given the open source nature of {pn_Rancher} and the underlying software components, you can simplify management and make significant IT savings as you scale orchestrated, microservice deployments anywhere you need to and for whatever use cases are needed in an agile and innovative way.
endif::focusRancher[]
ifdef::focusK3s[]
* Given the open source nature of {pn_K3s} and the minimal underlying software components, you can expand into a very distributed ecosystem, bringing computing to where the data exists or arrives, to answer the necessary business needs.
endif::focusK3s[]
ifdef::focusRKE1[]
* Given the open source nature of {pn_RKE1} and the underlying software components, you can simplify deployment with automation, maintain secure production instance and make significant IT savings as you scale orchestrated, microservice deployments anywhere you need to and for whatever use cases are needed in an agile and innovative way.
endif::focusRKE1[]
ifdef::focusRKE2[]
* Given the open source nature of {pn_RKE2} and the underlying software components, you can simplify deployment with automation, maintain secure production instance and make significant IT savings as you scale orchestrated, microservice deployments anywhere you need to and for whatever use cases are needed in an agile and innovative way.
endif::focusRKE2[]



