
==== {vn_LNVGY} {familyLNVGY-System} {modelLNVGY-SE350}

NOTE: The  {familyLNVGY-System} {modelLNVGY-SE350} is {companyName} YES Certified Hardware.

link:{modelLNVGY-SE350URL}[{vn_LNVGY} {familyLNVGY-System} {modelLNVGY-SE350}]::
The {familyLNVGY-System} {modelLNVGY-SE350} is a purpose-built server that is half the width and significantly shorter than a traditional server, making it ideal for deployment in tight spaces. It can be mounted on a wall, stacked on a shelf or mounted in a rack. The ThinkSystem SE350 puts increased processing power, storage and network closer to where data is generated, allowing actions resulting from the analysis of that data to take place more quickly.
** 4–16 server cores with up to 256 GB of memory
** broad-wired and wireless connectivity
** rugged, extended operating temperature of 0–55°C, up to 40G shock & 3Grms vibration with optional dust filter
** up to 16 TB of SSD storage
** small form factors with flexible mounting options
** low-touch deployment
** highly secure with optional SED encrypted storage for user data, as well as motion and intrusion tamper detection

// The {familyLNVGY-System} {modelLNVGY-SE350} is the latest workhorse for the edge. Designed and built with the unique requirements for edge servers in mind, it is versatile enough to stretch the limitations of server locations, providing a variety of connectivity and security options and easily managed with {vn_LNVGY_BMC}. The {familyLNVGY-System} {modelLNVGY-SE350} is a rugged compact-sized Edge solution with a focus on smart connectivity, business security, and manageability for the harsh environment and is a purpose-built edge compute server:
