

==== {vn_LNVGY} {familyLNVGY-Edge} {modelLNVGY-SE450}

NOTE: The  {familyLNVGY-Edge} {modelLNVGY-SE450} is {companyName} YES Certified 
Hardware.

link:{modelLNVGY-SE450URL}[{vn_LNVGY} {familyLNVGY-Edge} {modelLNVGY-SE450}]::
The {familyLNVGY-Edge} {modelLNVGY-SE450} is a single-socket server, with a 2U height and short depth case that can go almost anywhere. It can be mounted on a wall, placed on the floor like a tower server, or mounted in a rack. This rugged edge server can handle continuous operating temperatures from 5°C to 45°C, and some configurations are designed to meet NEBS Level-3 and ETSI requirements for 96 hours operating excursions from –5°C to 55°C as well as tolerance to locations with high dust and vibration. The {familyLNVGY-Edge} {modelLNVGY-SE450} is based on the 3rd Gen Intel Xeon Scalable processor and is designed to virtualize traditional IT applications as well as new transformative AI systems, providing the processing power, storage, accelerator, and networking technologies required for today’s edge workloads. 

** 10-36 server cores with up to 1TB of memory
** broad-wired and wireless connectivity
** supports up to four single-width GPUs or two double-wide GPUs
** offers up to four PCIe 4.0 slots plus a slot dedicated to the OCP adapter
** offer additional physical security features like chassis intrusion switch and lockable front beze

// The {familyLNVGY-Edge} {modelLNVGY-SE450} is the latest server for AI at the Edge. Designed and built with the unique requirements for Edge servers in mind, it is versatile enough to stretch the limitations of server locations, providing a variety of connectivity and security options and easily managed with {vn_LNVGY_BMC}. The {familyLNVGY-Edge} {modelLNVGY-SE450} is a rugged compact-sized Edge AI server focused on enhanced processing power, increased security, and remote manageability for edge environments: 

