
=== Security

FixMe - Neque viverra justo nec ultrices dui. Molestie a iaculis at erat. A lacus vestibulum sed arcu non odio euismod. Integer enim neque volutpat ac tincidunt vitae semper quis. Convallis a cras semper auctor neque vitae tempus quam pellentesque. Convallis a cras semper auctor neque vitae tempus quam. Nulla at volutpat diam ut venenatis tellus in. Amet consectetur adipiscing elit pellentesque. Pulvinar mattis nunc sed blandit libero volutpat sed. Egestas dui id ornare arcu odio. At lectus urna duis convallis convallis tellus id. Orci nulla pellentesque dignissim enim. In fermentum et sollicitudin ac orci phasellus. Tortor condimentum lacinia quis vel. Vitae aliquet nec ullamcorper sit amet risus nullam. Et leo duis ut diam quam nulla porttitor. Pellentesque habitant morbi tristique senectus et netus et. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Cras sed felis eget velit aliquet sagittis id consectetur.

ifdef::FLVR[]

ifdef::PoC[]
include::./PoC/SA.adoc[]
endif::PoC[]

ifdef::Production[]
include::./Production/SA.adoc[]
endif::Production[]

ifdef::Scaling[]
include::./Scaling/SA.adoc[]
endif::Scaling[]

endif::FLVR[]
