//include::./dellpoweredge_vars.adoc[]

==== {modelDell_server_node_R640} Rack Servers

{modelDell_server_node_R640_URL}

The PowerEdge R640 is SUSE YES Certified Hardware.

Uncompromising performance and density: 

The PowerEdge R640 is the ideal dual-socket, 1U platform for dense scale-out data center computing. The R640 combines density, performance and scalability to optimize application performance and data center density


•       CPU: Up to two 2nd Generation Intel® Xeon® Scalable processors with up to 28 cores per processor
•       Accelerators: Up to one single-width FPGA, Up to three single-width GPU (NVIDIA T4)
•       Memory Speed: DIMM Speed (Up to 2933MT/s)
•       Memory Type: RDIMM, LRDIMM, NVDIMM, DCPMM (Intel® Optane™ DC persistent memory)
•       Memory Module Slots: 24 DDR4 DIMM slots (12 NVDIMM or 12 DCPMM only)
Supports registered ECC DDR4 DIMMs only
•       Memory RAM: RDIMM 1.53TB, LRDIMM 3TB, NVDIMM 192GB, DCPMM 6.14TB (7.68TB with LRDIMM)  
•       Storage - Front Bays: Up to 10 x 2.5” with up to 8 NVMe, SAS/SATA/SSD/NVMe, max 76.8TB 
	Up to 10 NVMe, max 64TB 
	Up to 4 x 3.5” SAS/SATA, max 56T
•       Storage - Read Bays: Up to 2 x 2.5” SAS/SATA/SSD/NVMe, max 15.36TB 

For more information, see {modelDell-server-node-R640-datasheet}, {modelDell-server-node-R640-datasheet-URL}

Maximize application performance and density:

The scalable business architecture of the R640 is designed to maximize application performance and provide the flexibility to optimize configurations based on the application and use case. With the R640 you can create an NVMe cache pool and use either 2.5” or 3.5” drives for data storage. Combined with up to 24 DIMM’s, 12 of which can be DCPMMs or  NVDIMMs, you have the resources to maximize application performance with the optimum configuration in only a 1U chassis.

•       Simplify deployments and speed deployments with Dell EMC ready nodes for ScaleIO and VSAN.
•       Maximize storage performance with up to 10 NVMe drives or 12 2.5” drives.
•       Scale compute resources with 2nd Generation Intel® Xeon® Scalable processors and tailor performance based on your unique workload requirements.

Automate maintenance with Dell EMC OpenManage:

The Dell EMC OpenManage™ portfolio helps deliver peak efficiency for PowerEdge servers, delivering intelligent, automated management of routine tasks. Combined with unique agent-free management capabilities, the R640 is simply managed, freeing up time for high profile projects.

•       Simplify management with the OpenManage Enterprise™ console, with customized reporting and automatic discovery.
•       Take advantage of QuickSync 2 capabilities and gain access to your servers easily through your phone or tablet.

Guard your data center with built in security:

Every PowerEdge server is designed as part of a cyber resilient architecture, integrating security into the full server life cycle. The R640 leverages new security features built-into every new PowerEdge server strengthening protection so you can reliably and securely deliver accurate data to your customers no matter where they are. By considering each aspect of system security, from design to retirement, Dell EMC ensures trust and delivers a worry-free, secure infrastructure without compromise.

•       Rely on a secure component supply chain to ensure protection from factory to the data center.
•       Maintain data safety with cryptographically signed firmware packages and Secure Boot.
•       Prevent unauthorized or malicious change with Server Lockdown.
•       Wipe all data from storage media including hard drives, SSDs and system memory quickly and securely with System Erase.


