//include::./dellpoweredge_vars.adoc[]

==== {modelDell-server-node-R740} Rack Servers

{modelDell-server-node-R740-URL}

The PowerEdge R740 is SUSE YES Certified Hardware.

Optimized for workload acceleration:

The PowerEdge R740 was designed to accelerate application performance leveraging accelerator card and storage scalability. The 2-socket, 2U platform has the optimum balance of resources to power the most demanding environments

•       CPU: Up to two 2nd Generation Intel® Xeon® Scalable processors with up to 28 cores per processor
•       Accelerator: Up to three 300W or six 150W GPUs, Up to three double-width or four single-width FPGAs
•       Memory RDIMM, LRDIMM, NVDIMM, DCPMM (Intel® Optane™ DC persistent memory)
•       Memory Module Slots: 24 DDR4 DIMM slots (12 NVDIMM or 12 DCPMM only), Supports registered ECC DDR4 DIMMs only 
•       Memory RAM: RDIMM 1.53TB, LRDIMM 3TB, NVDIMM 192GB, DCPMM 6.14TB (7.68TB with LRDIMM)  
•       Storage - Front Bays: Up to 16 x 2.5” SAS/SATA/SSD, max 122.88TB, Up to 8 x 3.5” SAS/SATA, max 128TB 

For more information, see {modelDell-server-node-R740-datasheet}, {modelDell-server-node-R740-datasheet-URL}

Expand and optimize application performance:

The scalable business architecture of the R740 can scale up to three 300W or six 150W GPUs, or up to three double-width or four single-width FPGAs. With up to 16 2.5” drives or 8 3.5” drives the R740 provides the versatility to adapt to virtually any application and provides the perfect platform for VDI deployments.

•       Scale your VDI deployments with 3 double-width GPUs, supporting up to 50% more users when compared to R730.
•       Free up storage space using internal M.2 SSDs optimized for boot.
•       Scale compute resources with 2nd Generation Intel® Xeon® Scalable processors and tailor performance based on your unique workload requirements.

Automate systems management with OpenManage:

The Dell EMC OpenManage™ portfolio helps deliver peak efficiency for PowerEdge servers, delivering intelligent, automated management of routine tasks. Combined with unique agent-free management capabilities, the R740 is simply managed, freeing up time for high profile projects.

•       Simplify management with the New OpenManage Enterprise™ console, with customized reporting and automatic discovery.
•       Take advantage of QuickSync 2 capabilities and gain access to your servers easily through your phone or tablet.

Rely on PowerEdge with built-in security:

Every PowerEdge server is designed as part of a cyber resilient architecture, integrating security into the full server lifecycle. The R740 leverages new security features built-into every new PowerEdge server strengthening protection so you can reliably and securely deliver accurate data to your customers no matter where they are. By considering each aspect of system security, from design to retirement, Dell EMC ensures trust and delivers a worry-free, secure infrastructure without compromise.

•       Rely on a secure component supply chain to ensure protection from factory to the data center.
•       Maintain data safety with cryptographically signed firmware packages and Secure Boot.
•       Prevent unauthorized or malicious change with Server Lockdown.
•       Wipe all data from storage media including hard drives, SSDs and system memory quickly and securely with System Erase
