//include::./dellpoweredge_vars.adoc[]

==== {modelDell-server-node-R750} Rack Servers

{modelDell-server-node-R750-URL}

The PowerEdge R750 is SUSE YES Certified Hardware.

General purpose server optimized to address the most demanding workloads

The Dell EMC PowerEdge R750, is a full-featured enterprise server, delivering outstanding performance for the most demanding workloads

•       CPU: Up to two 3rd Generation Intel Xeon Scalable processors, with up to 40 cores per processor
•       Memory: 32 DDR4 DIMM slots, supports RDIMM 2 TB max or LRDIMM 8 TB max, speeds up to 3200 MT/s, Up to 16 Intel Persistent Memory 200 series (BPS) slots, 8 TB max, Supports registered ECC DDR4 DIMMs only
•       Storage Controllers -  Internal controllers: PERC H745, HBA355I, S150, H345, H755, H755N
•       Storage Controllers -  Boot Optimized Storage Subsystem (BOSS-S2): HW RAID 2 x M.2 SSDs 240 GB or 480 GB
•       Storage Controllers - External PERC (RAID): PERC H840, HBA355E
•       Drive Bays - Front bays: Up to 12 x 3.5-inch SAS/SATA (HDD/SSD) max 192 TB, Up to 8 x 2.5-inch NVMe (SSD) max 122.88 TB, Up to 16 x 2.5-inch SAS/SATA/NVMe (HDD/SSD) max 245.76 TB, Up to 24 x 2.5-inch SAS/SATA/NVMe (HDD/SSD) max 368.84 TB
•       Drive Bays - Rear bays: Rear bays: Up to 2 x 2.5-inch SAS/SATA/NVMe (HDD/SSD) max 30.72 TB, Up to 4 x 2.5-inch SAS/SATA/NVMe (HDD/SSD) max 61.44 TB 

For more information, see {modelDell-server-node-R750-datasheet}, {modelDell-server-node-R750-datasheet-URL}

Innovate at scale with challenging and emerging workloads

The Dell EMC PowerEdge R750, powered by the 3rd Generation Intel® Xeon® Scalable processors is a rack server to address application performance and acceleration. The PowerEdge R750, is a dual-socket/2U rack server that delivers outstanding performance for the most demanding workloads. It supports 8 channels of memory per CPU, and up to 32 DDR4 DIMMs @ 3200 MT/s speeds. In addition, to address substantial throughput improvements the PowerEdge R750 supports PCIe Gen 4 and up to 24 NVMe drives with improved air-cooling features and optional Direct Liquid Cooling to support increasing power and thermal requirements. This makes the PowerEdge R750 an ideal server for data center standardization on a wide range of workloads including; Database and Analytics, Highperformance computing (HPC), Traditional corporate IT, Virtual Desktop Infrastructure, and AI/ML environments that require performance, extensive storage and GPU support

Increase efficiency and accelerate operations with autonomous collaboration

The Dell EMC OpenManage systems management portfolio tames the complexity of managing and securing IT infrastructure. Using Dell Technologies’ intuitive end-to-end tools, IT can deliver a secure, integrated experience by reducing process and information silos in order to focus on growing the business. The Dell EMC OpenManage portfolio is the key to your innovation engine, unlocking the tools and automation that help you scale, manage, and protect your technology environment.

•	Built-in telemetry streaming, thermal management, and RESTful API with Redfish offer streamlined visibility and control for better server management
•	Intelligent automation lets you enable cooperation between human actions and system capabilities for added productivity
•	Integrated change management capabilities for update planning and seamless, zero-touch configuration and implementation
•	Full-stack management integration with Microsoft, VMware, ServiceNow, Ansible and many other tool

Protect your data assets and infrastructure with proactive resilience

The Dell EMC PowerEdge R750 server is designed with a cyber-resilient architecture, integrating security deeply into every phase in the lifecycle, from design to retirement.

•	Operate your workloads on a secure platform anchored by cryptographically trusted booting and silicon root of trust
•	Maintain server firmware safety with digitally signed firmware packages
•	Prevent unauthorized configuration or firmware change with system lockdown
•	Securely and quickly wipe all data from storage media, including hard drives, SSDs and system memory with System Erase
