
ifdef::iRKE1[]

=== Business problem

Many organizations are deploying Kubernetes clusters everywhere – in the cloud, on-premises, and at the edge - to unify IT operations.  Such organizations can realize dramatic benefits, including:

* Consistently deliver a high level of reliability on any infrastructure
* Improve DevOps efficiency with standardized automation
* Ensure enforcement of security policies on any infrastructure

However, simply relying on upstream Kubernetes alone can introduce extra overhead and risk because Kubernetes clusters are typically deployed:

* Without central visibility
* Without consistent security policies
* And must be managed independently

Deploying a scalable kubernetes infrastructure requires consideration of a larger ecosystem, encompassing many software and infrastructure components and providers. Further, the ability to continually address the needs and concerns of:

Developers::
For those who just focus on writing code to build their apps securely using a preferred workflow, providing a simple, push-button deployment mechanism of their containerized workloads where needed.

IT Operators::
General infrastructure requirements still rely upon traditional IT pillars are for the stacked, underlying infrastructure. Ease of deployment, availability, scalability, resiliency, performance, security and integrity are still core concerns to be addressed for administrative control and observability.

ifdef::RC[]
Beyond just the core infrastructure software layers of managed Kubernetes clusters, organizations may be also be impacted by:

ifdef::iISV[]
Workloads::
Scaling, lifecycle management, consistency of the distributed deployment of services and applications
endif::iISV[]

ifdef::iCSP,iIHV[]
Compute Platform::
Potential inconsistencies and impacts of multiple target system platforms for the distributed deployments of the cluster elements, across:

ifdef::iIHV[]
* physical, baremetal, hypervisors and virtual machines
endif::iIHV[]
ifdef::iCSP[]
* pay-as-you-go, bring-your-own, or hosted Kubernetes services
endif::iCSP[]
endif::iCSP,iIHV[]

endif::RC[]

endif::iRKE1[]

ifdef::iRKE1[]

=== Business value

With {pn_RKE1}, the operation of Kubernetes is easily automated and entirely independent of the operating system and platform running. Using a supported version of the container runtime engine, one can deploy and run Kubernetes with {pn_RKE1}. It builds a cluster from a single command in just a few minutes, and its declarative configuration makes Kubernetes upgrades atomic and safe.


By allowing operation teams to focus on infrastructure and developers to deploy code the way they want too, {companyName} and the {portfolioName} offerings helps bring products to market faster and accelerate an organization’s digital transformation. 

{pn_Rancher} is a fundamental part of the complete software stack for teams adopting containers. It provides DevOps teams with integrated tools for running containerized workloads while also addressing the operational and security challenges of managing multiple Kubernetes clusters across any targetedd infrastructure.

Developers::
{pn_Rancher} makes it easy to securely deploy containerized applications no matter where the Kubernetes infrastructure runs -– in the cloud, on-premises, or at the edge.  Using Helm or the App Catalog to deploy and manage applications across any or all these environments, ensuring multi-cluster consistency with a single deployment process. 

IT Operators::
{pn_Rancher} not only deploys and manages production-grade Kubernetes clusters from datacenter to cloud to the edge, it also unites them with centralized authentication, access control and observability. Further, it streamlines cluster deployment on bare metal or virtual machines and maintains them using defined security policies.

// NOTE:: For further information, visit {suseWhyPage}[{companyName}] and {rancherWhyPage}[{portfolioName}].

ifdef::RC[]
With this increased consistency of the managed Kubernetes infrastructure clusters, organizations benefit from an even higher level of the Cloud Native Computing model where each layer only relies upon the API and version of the adjacent layer. For example:

ifdef::iISV[]
Workloads::
Each managed cluster has defined access control and a designated Kubernetes version, so deployment containerized services can easily be scaled to other compatible clusters
endif::iISV[]

ifdef::iCSP,iIHV[]
ifdef::iIHV[]
ifdef::IHV-Cisco[include::../IHV/Cisco/SA-RA-BPBV.adoc[]]
ifdef::IHV-DELL[include::../IHV/DELL/SA-RA-BPBV.adoc[]]
ifdef::IHV-HPE[include::../IHV/HPE/SA-RA-BPBV.adoc[]]
ifdef::IHV-Supermicro[include::../IHV/Supermicro/SuperServer/SA-RA-BPBV.adoc[]]
endif::iIHV[]
//ifdef::iCSP[]
//FixMe
//endif::iCSP[]
endif::iCSP,iIHV[]

endif::RC[]

endif::iRKE1[]

